package server

import (
	"context"
	"crypto/x509"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"p2pstream/internal/config"
	"p2pstream/internal/secrets"
)

func TestNewManagementTLSConfigAutoGeneratesVerifiableCertificate(t *testing.T) {
	cfg := managementTLSTestConfig(t)
	cfg.ManagementPort = "9443"
	cfg.ManagementAdvertiseHost = "10.42.0.5"
	cfg.ManagementTLSExtraHosts = "example.test,192.0.2.10"

	tlsConfig, enabled, err := NewManagementTLSConfig(cfg)
	if err != nil {
		t.Fatalf("NewManagementTLSConfig() error = %v", err)
	}
	if !enabled {
		t.Fatal("expected management TLS to be enabled")
	}
	if tlsConfig == nil || len(tlsConfig.Certificates) != 1 {
		t.Fatalf("unexpected TLS config: %+v", tlsConfig)
	}
	if !cfg.ManagementTLSAutoGenerated {
		t.Fatal("expected auto-generated management TLS metadata")
	}
	if cfg.ManagementDefaultURL != "https://10.42.0.5:9443" {
		t.Fatalf("ManagementDefaultURL = %q", cfg.ManagementDefaultURL)
	}
	if cfg.ManagementCAPEM == "" || cfg.ManagementCASHA256 == "" {
		t.Fatalf("expected management CA metadata to be exposed: %+v", cfg)
	}

	for _, path := range []string{
		filepath.Join(cfg.CertsDir, "management", "ca.crt.pem"),
		filepath.Join(cfg.CertsDir, "management", "ca.key.pem"),
		filepath.Join(cfg.CertsDir, "management", "server.crt.pem"),
		filepath.Join(cfg.CertsDir, "management", "server.key.pem"),
	} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected generated TLS file %s: %v", path, err)
		}
	}

	roots := x509.NewCertPool()
	if !roots.AppendCertsFromPEM([]byte(cfg.ManagementCAPEM)) {
		t.Fatal("management CA PEM did not parse")
	}
	cert, err := x509.ParseCertificate(tlsConfig.Certificates[0].Certificate[0])
	if err != nil {
		t.Fatalf("parse server certificate: %v", err)
	}
	for _, host := range []string{"10.42.0.5", "localhost", "server", "p2pstream.local", "example.test", "192.0.2.10"} {
		if _, err := cert.Verify(x509.VerifyOptions{Roots: roots, DNSName: host}); err != nil {
			t.Fatalf("generated management certificate did not verify for %s: %v", host, err)
		}
	}
}

func TestNewManagementTLSConfigUsesPublicURLForDefaultAndSAN(t *testing.T) {
	cfg := managementTLSTestConfig(t)
	cfg.ManagementPublicURL = "https://proxy.example.test:9443/admin/"

	tlsConfig, enabled, err := NewManagementTLSConfig(cfg)
	if err != nil {
		t.Fatalf("NewManagementTLSConfig() error = %v", err)
	}
	if !enabled || tlsConfig == nil {
		t.Fatal("expected management TLS to be enabled")
	}
	if cfg.ManagementDetectedAdvertiseHost != "proxy.example.test" {
		t.Fatalf("ManagementDetectedAdvertiseHost = %q", cfg.ManagementDetectedAdvertiseHost)
	}
	if cfg.ManagementDefaultURL != "https://proxy.example.test:9443/admin" {
		t.Fatalf("ManagementDefaultURL = %q", cfg.ManagementDefaultURL)
	}

	roots := x509.NewCertPool()
	if !roots.AppendCertsFromPEM([]byte(cfg.ManagementCAPEM)) {
		t.Fatal("management CA PEM did not parse")
	}
	cert, err := x509.ParseCertificate(tlsConfig.Certificates[0].Certificate[0])
	if err != nil {
		t.Fatalf("parse server certificate: %v", err)
	}
	if _, err := cert.Verify(x509.VerifyOptions{Roots: roots, DNSName: "proxy.example.test"}); err != nil {
		t.Fatalf("generated management certificate did not verify for public URL host: %v", err)
	}
}

func TestNewManagementTLSConfigWithSecretsEncryptsAutoGeneratedKeys(t *testing.T) {
	cfg := managementTLSTestConfig(t)
	service, err := secrets.NewService(secrets.KeyConfig{
		CurrentKey:     testSecretsEncryptionKey(),
		CurrentKeyID:   "current",
		AllowPlaintext: true,
	})
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}

	tlsConfig, enabled, err := NewManagementTLSConfigWithSecrets(context.Background(), cfg, service)
	if err != nil {
		t.Fatalf("NewManagementTLSConfigWithSecrets() error = %v", err)
	}
	if !enabled || tlsConfig == nil || len(tlsConfig.Certificates) != 1 {
		t.Fatalf("unexpected TLS config: enabled=%v config=%+v", enabled, tlsConfig)
	}

	for _, path := range []string{
		filepath.Join(cfg.CertsDir, "management", "ca.key.pem"),
		filepath.Join(cfg.CertsDir, "management", "server.key.pem"),
	} {
		stored, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if !secrets.IsEncrypted(string(stored)) || strings.Contains(string(stored), "PRIVATE KEY") {
			t.Fatalf("generated key %s was not encrypted: %q", path, stored)
		}
	}
	for _, path := range []string{
		filepath.Join(cfg.CertsDir, "management", "ca.crt.pem"),
		filepath.Join(cfg.CertsDir, "management", "server.crt.pem"),
	} {
		stored, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if !strings.Contains(string(stored), "BEGIN CERTIFICATE") {
			t.Fatalf("generated certificate %s is not plaintext PEM", path)
		}
	}

	secondConfig, secondEnabled, err := NewManagementTLSConfigWithSecrets(context.Background(), cfg, service)
	if err != nil {
		t.Fatalf("second NewManagementTLSConfigWithSecrets() error = %v", err)
	}
	if !secondEnabled || secondConfig == nil || len(secondConfig.Certificates) != 1 {
		t.Fatalf("unexpected second TLS config: enabled=%v config=%+v", secondEnabled, secondConfig)
	}
}

func TestNewManagementTLSConfigOffModeRequiresExplicitInsecureHTTP(t *testing.T) {
	cfg := managementTLSTestConfig(t)
	cfg.ManagementTLSMode = "off"
	cfg.ManagementAdvertiseHost = "localhost"

	if _, _, err := NewManagementTLSConfig(cfg); err == nil {
		t.Fatal("expected off mode without insecure opt in to fail")
	}

	cfg.ManagementAllowInsecureHTTP = true
	tlsConfig, enabled, err := NewManagementTLSConfig(cfg)
	if err != nil {
		t.Fatalf("NewManagementTLSConfig() error = %v", err)
	}
	if enabled || tlsConfig != nil {
		t.Fatalf("expected HTTP management config, got enabled=%v tlsConfig=%+v", enabled, tlsConfig)
	}
	if cfg.ManagementDefaultURL != "http://localhost:8081" {
		t.Fatalf("ManagementDefaultURL = %q", cfg.ManagementDefaultURL)
	}
}

func managementTLSTestConfig(t *testing.T) *config.Config {
	t.Helper()
	dir := t.TempDir()
	return &config.Config{
		ManagementPort:    "8081",
		ConfigDir:         dir,
		CertsDir:          filepath.Join(dir, "certs"),
		ManagementTLSMode: "auto",
	}
}
