package server

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"p2pstream/internal/config"
)

const (
	managementTLSModeAuto     = "auto"
	managementTLSModeProvided = "provided"
	managementTLSModeOff      = "off"

	managementCertDirName    = "management"
	managementCACertFileName = "ca.crt.pem"
	managementCAKeyFileName  = "ca.key.pem"
	managementCertFileName   = "server.crt.pem"
	managementKeyFileName    = "server.key.pem"
)

// NewManagementTLSConfig builds the TLS configuration for the management API.
// The boolean return value is true when the management listener should serve TLS.
func NewManagementTLSConfig(cfg *config.Config) (*tls.Config, bool, error) {
	if cfg == nil {
		return nil, false, nil
	}

	mode := strings.ToLower(strings.TrimSpace(cfg.ManagementTLSMode))
	if mode == "" {
		mode = managementTLSModeAuto
	}
	advertiseHost := detectManagementAdvertiseHost(cfg)

	if mode == managementTLSModeOff {
		if !cfg.ManagementAllowInsecureHTTP {
			return nil, false, fmt.Errorf("MANAGEMENT_TLS_MODE=off requires MANAGEMENT_ALLOW_INSECURE_HTTP=true")
		}
		recordManagementSecurity(cfg, false, false, advertiseHost, "", "")
		return nil, false, nil
	}

	certFile := strings.TrimSpace(cfg.ManagementTLSCertFile)
	keyFile := strings.TrimSpace(cfg.ManagementTLSKeyFile)
	autoGenerated := false
	caPEM := ""

	if certFile == "" || keyFile == "" {
		if mode == managementTLSModeProvided {
			return nil, false, fmt.Errorf("MANAGEMENT_TLS_MODE=provided requires MANAGEMENT_TLS_CERT_FILE and MANAGEMENT_TLS_KEY_FILE")
		}
		generated, err := ensureAutoManagementTLSFiles(cfg, advertiseHost)
		if err != nil {
			return nil, false, err
		}
		certFile = generated.certFile
		keyFile = generated.keyFile
		caPEM = string(generated.caPEM)
		autoGenerated = true
	}

	cert, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, false, fmt.Errorf("load management TLS certificate: %w", err)
	}

	tlsConfig := &tls.Config{
		MinVersion:   tls.VersionTLS12,
		Certificates: []tls.Certificate{cert},
	}

	if cfg.ManagementTLSClientCAFile != "" {
		clientCAs, err := loadCertPool(cfg.ManagementTLSClientCAFile)
		if err != nil {
			return nil, false, fmt.Errorf("load management client CA: %w", err)
		}
		tlsConfig.ClientCAs = clientCAs
		tlsConfig.ClientAuth = tls.VerifyClientCertIfGiven
	}

	recordManagementSecurity(cfg, true, autoGenerated, advertiseHost, caPEM, managementCAPEMSHA256(caPEM))
	return tlsConfig, true, nil
}

func recordManagementSecurity(cfg *config.Config, tlsEnabled bool, autoGenerated bool, advertiseHost string, caPEM string, caSHA256 string) {
	cfg.ManagementTLSEnabled = tlsEnabled
	cfg.ManagementTLSAutoGenerated = autoGenerated
	cfg.ManagementDetectedAdvertiseHost = advertiseHost
	cfg.ManagementDefaultURL = defaultManagementURL(cfg, advertiseHost, tlsEnabled)
	cfg.ManagementCAPEM = caPEM
	cfg.ManagementCASHA256 = caSHA256
}

func defaultManagementURL(cfg *config.Config, advertiseHost string, tlsEnabled bool) string {
	if cfg != nil && strings.TrimSpace(cfg.ManagementPublicURL) != "" {
		return strings.TrimRight(strings.TrimSpace(cfg.ManagementPublicURL), "/")
	}
	scheme := "https"
	if !tlsEnabled {
		scheme = "http"
	}
	port := "8081"
	if cfg != nil && strings.TrimSpace(cfg.ManagementPort) != "" {
		port = strings.TrimSpace(cfg.ManagementPort)
	}
	host := strings.TrimSpace(advertiseHost)
	if host == "" {
		host = "localhost"
	}
	return (&url.URL{Scheme: scheme, Host: joinHostPort(host, port)}).String()
}

type autoManagementTLSFiles struct {
	certFile string
	keyFile  string
	caPEM    []byte
}

func ensureAutoManagementTLSFiles(cfg *config.Config, advertiseHost string) (autoManagementTLSFiles, error) {
	managementDir := filepath.Join(managementCertBaseDir(cfg), managementCertDirName)
	if err := os.MkdirAll(managementDir, 0700); err != nil {
		return autoManagementTLSFiles{}, fmt.Errorf("create management TLS directory: %w", err)
	}
	if err := os.Chmod(managementDir, 0700); err != nil {
		return autoManagementTLSFiles{}, fmt.Errorf("set management TLS directory permissions: %w", err)
	}

	files := autoManagementTLSFiles{
		certFile: filepath.Join(managementDir, managementCertFileName),
		keyFile:  filepath.Join(managementDir, managementKeyFileName),
	}
	caCertFile := filepath.Join(managementDir, managementCACertFileName)
	caKeyFile := filepath.Join(managementDir, managementCAKeyFileName)

	caCertPEM, caKeyPEM, caCert, caKey, err := loadOrCreateManagementCA(caCertFile, caKeyFile)
	if err != nil {
		return autoManagementTLSFiles{}, err
	}
	files.caPEM = caCertPEM

	hosts := managementTLSHosts(cfg, advertiseHost)
	needsLeaf := true
	if certPEM, err := os.ReadFile(files.certFile); err == nil {
		if block, _ := pem.Decode(certPEM); block != nil {
			if cert, err := x509.ParseCertificate(block.Bytes); err == nil &&
				managementCertificateMatchesHosts(cert, hosts) &&
				managementCertificateVerifiesWithCA(cert, caCert, hosts) {
				if _, err := tls.LoadX509KeyPair(files.certFile, files.keyFile); err == nil {
					needsLeaf = false
				}
			}
		}
	}
	if needsLeaf {
		certPEM, keyPEM, err := generateManagementServerCertificatePEM(caCert, caKey, hosts)
		if err != nil {
			return autoManagementTLSFiles{}, fmt.Errorf("generate management TLS certificate: %w", err)
		}
		if err := writePEMFile(files.certFile, certPEM, 0644); err != nil {
			return autoManagementTLSFiles{}, fmt.Errorf("write management TLS certificate: %w", err)
		}
		if err := writePEMFile(files.keyFile, keyPEM, 0600); err != nil {
			return autoManagementTLSFiles{}, fmt.Errorf("write management TLS key: %w", err)
		}
	}
	_ = caKeyPEM
	return files, nil
}

func managementCertBaseDir(cfg *config.Config) string {
	if cfg != nil && strings.TrimSpace(cfg.CertsDir) != "" {
		return cfg.CertsDir
	}
	configDir := config.DefaultConfigDir
	if cfg != nil && strings.TrimSpace(cfg.ConfigDir) != "" {
		configDir = cfg.ConfigDir
	}
	return filepath.Join(filepath.Clean(configDir), "certs")
}

func loadOrCreateManagementCA(certFile string, keyFile string) ([]byte, []byte, *x509.Certificate, *rsa.PrivateKey, error) {
	if certPEM, certErr := os.ReadFile(certFile); certErr == nil {
		if keyPEM, keyErr := os.ReadFile(keyFile); keyErr == nil {
			cert, key, err := parseManagementCA(certPEM, keyPEM)
			if err == nil {
				return certPEM, keyPEM, cert, key, nil
			}
		}
	}

	certPEM, keyPEM, cert, key, err := generateManagementCAPEM()
	if err != nil {
		return nil, nil, nil, nil, fmt.Errorf("generate management CA: %w", err)
	}
	if err := writePEMFile(certFile, certPEM, 0644); err != nil {
		return nil, nil, nil, nil, fmt.Errorf("write management CA certificate: %w", err)
	}
	if err := writePEMFile(keyFile, keyPEM, 0600); err != nil {
		return nil, nil, nil, nil, fmt.Errorf("write management CA key: %w", err)
	}
	return certPEM, keyPEM, cert, key, nil
}

func parseManagementCA(certPEM []byte, keyPEM []byte) (*x509.Certificate, *rsa.PrivateKey, error) {
	certBlock, _ := pem.Decode(certPEM)
	if certBlock == nil {
		return nil, nil, fmt.Errorf("management CA certificate is not PEM")
	}
	cert, err := x509.ParseCertificate(certBlock.Bytes)
	if err != nil {
		return nil, nil, err
	}
	keyBlock, _ := pem.Decode(keyPEM)
	if keyBlock == nil {
		return nil, nil, fmt.Errorf("management CA key is not PEM")
	}
	key, err := x509.ParsePKCS1PrivateKey(keyBlock.Bytes)
	if err != nil {
		return nil, nil, err
	}
	if !cert.IsCA {
		return nil, nil, fmt.Errorf("management CA certificate is not a CA")
	}
	return cert, key, nil
}

func generateManagementCAPEM() ([]byte, []byte, *x509.Certificate, *rsa.PrivateKey, error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, nil, nil, nil, err
	}
	now := time.Now()
	template := &x509.Certificate{
		SerialNumber:          randomSerialNumber(),
		Subject:               pkix.Name{CommonName: "p2pstream management local CA"},
		NotBefore:             now.Add(-time.Minute),
		NotAfter:              now.Add(10 * 365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        true,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		return nil, nil, nil, nil, err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, nil, nil, nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}),
		pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)}),
		cert,
		key,
		nil
}

func generateManagementServerCertificatePEM(caCert *x509.Certificate, caKey *rsa.PrivateKey, hosts []string) ([]byte, []byte, error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, nil, err
	}
	now := time.Now()
	template := &x509.Certificate{
		SerialNumber:          randomSerialNumber(),
		Subject:               pkix.Name{CommonName: "p2pstream management"},
		NotBefore:             now.Add(-time.Minute),
		NotAfter:              now.Add(10 * 365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
	}
	for _, host := range hosts {
		if ip := net.ParseIP(host); ip != nil {
			template.IPAddresses = append(template.IPAddresses, ip)
			continue
		}
		template.DNSNames = append(template.DNSNames, host)
	}
	der, err := x509.CreateCertificate(rand.Reader, template, caCert, &key.PublicKey, caKey)
	if err != nil {
		return nil, nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}),
		pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)}),
		nil
}

func managementTLSHosts(cfg *config.Config, advertiseHost string) []string {
	seen := make(map[string]struct{})
	var hosts []string
	add := func(host string) {
		host = normalizeManagementHost(host)
		if host == "" {
			return
		}
		if _, ok := seen[host]; ok {
			return
		}
		seen[host] = struct{}{}
		hosts = append(hosts, host)
	}

	add(advertiseHost)
	add("localhost")
	add("p2pstream.local")
	add("server")
	add("127.0.0.1")
	add("::1")
	if cfg != nil {
		for _, part := range strings.Split(cfg.ManagementTLSExtraHosts, ",") {
			add(part)
		}
	}
	return hosts
}

func managementCertificateMatchesHosts(cert *x509.Certificate, hosts []string) bool {
	if cert == nil {
		return false
	}
	now := time.Now()
	if now.Before(cert.NotBefore) || now.After(cert.NotAfter) {
		return false
	}
	for _, host := range hosts {
		if err := cert.VerifyHostname(host); err != nil {
			return false
		}
	}
	return true
}

func managementCertificateVerifiesWithCA(cert *x509.Certificate, caCert *x509.Certificate, hosts []string) bool {
	if cert == nil || caCert == nil || len(hosts) == 0 {
		return false
	}
	roots := x509.NewCertPool()
	roots.AddCert(caCert)
	_, err := cert.Verify(x509.VerifyOptions{
		Roots:     roots,
		DNSName:   hosts[0],
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	})
	return err == nil
}

func detectManagementAdvertiseHost(cfg *config.Config) string {
	if cfg != nil {
		if host := hostFromURL(cfg.ManagementPublicURL); host != "" {
			return host
		}
		if host := normalizeManagementHost(cfg.ManagementAdvertiseHost); host != "" {
			return host
		}
	}
	if host := defaultRouteLocalIP(); host != "" {
		return host
	}
	if host := firstNonLoopbackIPv4(); host != "" {
		return host
	}
	return "localhost"
}

func hostFromURL(rawURL string) string {
	rawURL = strings.TrimSpace(rawURL)
	if rawURL == "" {
		return ""
	}
	parsed, err := url.Parse(rawURL)
	if err != nil {
		return ""
	}
	return normalizeManagementHost(parsed.Hostname())
}

func defaultRouteLocalIP() string {
	conn, err := net.DialTimeout("udp", "1.1.1.1:443", 500*time.Millisecond)
	if err != nil {
		return ""
	}
	defer conn.Close()
	addr, ok := conn.LocalAddr().(*net.UDPAddr)
	if !ok || addr.IP == nil || addr.IP.IsLoopback() {
		return ""
	}
	return addr.IP.String()
}

func firstNonLoopbackIPv4() string {
	interfaces, err := net.Interfaces()
	if err != nil {
		return ""
	}
	for _, iface := range interfaces {
		if iface.Flags&net.FlagUp == 0 || iface.Flags&net.FlagLoopback != 0 {
			continue
		}
		addrs, err := iface.Addrs()
		if err != nil {
			continue
		}
		for _, addr := range addrs {
			var ip net.IP
			switch v := addr.(type) {
			case *net.IPNet:
				ip = v.IP
			case *net.IPAddr:
				ip = v.IP
			}
			if ip == nil || ip.IsLoopback() {
				continue
			}
			if ipv4 := ip.To4(); ipv4 != nil {
				return ipv4.String()
			}
		}
	}
	return ""
}

func normalizeManagementHost(host string) string {
	host = strings.TrimSpace(host)
	if host == "" {
		return ""
	}
	host = strings.TrimPrefix(host, "https://")
	host = strings.TrimPrefix(host, "http://")
	if strings.Contains(host, "/") {
		host = strings.Split(host, "/")[0]
	}
	if h, _, err := net.SplitHostPort(host); err == nil {
		host = h
	}
	host = strings.Trim(host, "[]")
	return strings.TrimSpace(host)
}

func joinHostPort(host string, port string) string {
	if strings.TrimSpace(port) == "" {
		return host
	}
	return net.JoinHostPort(strings.Trim(host, "[]"), port)
}

func writePEMFile(path string, contents []byte, mode os.FileMode) error {
	if err := os.WriteFile(path, contents, mode); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

func randomSerialNumber() *big.Int {
	serialLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, serialLimit)
	if err != nil {
		return big.NewInt(time.Now().UnixNano())
	}
	return serial
}

func managementCAPEMSHA256(caPEM string) string {
	if strings.TrimSpace(caPEM) == "" {
		return ""
	}
	sum := sha256.Sum256([]byte(caPEM))
	return hex.EncodeToString(sum[:])
}

func loadCertPool(path string) (*x509.CertPool, error) {
	pemBytes, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(pemBytes) {
		return nil, fmt.Errorf("no PEM certificates found in %q", path)
	}
	return pool, nil
}
