// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID                 int64        `json:"id"`
	PublicID           string       `json:"public_id"`
	Name               string       `json:"name"`
	TokenHash          string       `json:"token_hash"`
	Enabled            int64        `json:"enabled"`
	LastConnectedAt    sql.NullTime `json:"last_connected_at"`
	LastDisconnectedAt sql.NullTime `json:"last_disconnected_at"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
}

type AgentStat struct {
	ID               int64         `json:"id"`
	AgentID          sql.NullInt64 `json:"agent_id"`
	ReportedAt       time.Time     `json:"reported_at"`
	MemoryMb         int64         `json:"memory_mb"`
	Goroutines       int64         `json:"goroutines"`
	ReqSuccess       int64         `json:"req_success"`
	ReqClientError   int64         `json:"req_client_error"`
	ReqServerError   int64         `json:"req_server_error"`
	ReqInternalError int64         `json:"req_internal_error"`
	BytesRx          int64         `json:"bytes_rx"`
	BytesTx          int64         `json:"bytes_tx"`
	CpuPercent       float64       `json:"cpu_percent"`
}

type AgentStatRollupMinute struct {
	BucketUnixMillis int64     `json:"bucket_unix_millis"`
	Samples          int64     `json:"samples"`
	ReqSuccess       int64     `json:"req_success"`
	ReqClientError   int64     `json:"req_client_error"`
	ReqServerError   int64     `json:"req_server_error"`
	ReqInternalError int64     `json:"req_internal_error"`
	BytesRx          int64     `json:"bytes_rx"`
	BytesTx          int64     `json:"bytes_tx"`
	MemoryMbSum      int64     `json:"memory_mb_sum"`
	MaxMemoryMb      int64     `json:"max_memory_mb"`
	GoroutinesSum    int64     `json:"goroutines_sum"`
	MaxGoroutines    int64     `json:"max_goroutines"`
	CpuPercentSum    float64   `json:"cpu_percent_sum"`
	MaxCpuPercent    float64   `json:"max_cpu_percent"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Connection struct {
	ID             int64         `json:"id"`
	AgentID        sql.NullInt64 `json:"agent_id"`
	ConnectedAt    time.Time     `json:"connected_at"`
	DisconnectedAt sql.NullTime  `json:"disconnected_at"`
}

type Environment struct {
	ID                            int64         `json:"id"`
	Name                          string        `json:"name"`
	ManagementUrl                 string        `json:"management_url"`
	Transport                     string        `json:"transport"`
	AgentID                       sql.NullInt64 `json:"agent_id"`
	AccessToken                   string        `json:"access_token"`
	TrustedCertificatePem         string        `json:"trusted_certificate_pem"`
	TrustedCertificateSha256      string        `json:"trusted_certificate_sha256"`
	TrustedCertificateSubject     string        `json:"trusted_certificate_subject"`
	TrustedCertificateNotAfter    sql.NullTime  `json:"trusted_certificate_not_after"`
	LastObservedCertificatePem    string        `json:"last_observed_certificate_pem"`
	LastObservedCertificateSha256 string        `json:"last_observed_certificate_sha256"`
	ResponseHeaderTimeoutMillis   int64         `json:"response_header_timeout_millis"`
	Enabled                       int64         `json:"enabled"`
	LastCheckedAt                 sql.NullTime  `json:"last_checked_at"`
	LastError                     string        `json:"last_error"`
	CreatedAt                     time.Time     `json:"created_at"`
	UpdatedAt                     time.Time     `json:"updated_at"`
}

type ManagementAccessToken struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	TokenHash  string       `json:"token_hash"`
	Role       string       `json:"role"`
	Enabled    int64        `json:"enabled"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type ObservabilityRollupState struct {
	ID                       int64     `json:"id"`
	ProxyBackfillUpperID     int64     `json:"proxy_backfill_upper_id"`
	ProxyBackfilledThroughID int64     `json:"proxy_backfilled_through_id"`
	AgentBackfillUpperID     int64     `json:"agent_backfill_upper_id"`
	AgentBackfilledThroughID int64     `json:"agent_backfilled_through_id"`
	CreatedAt                time.Time `json:"created_at"`
	UpdatedAt                time.Time `json:"updated_at"`
}

type ProxyRequestEvent struct {
	ID            int64         `json:"id"`
	OccurredAt    time.Time     `json:"occurred_at"`
	StatusCode    int64         `json:"status_code"`
	DurationMs    int64         `json:"duration_ms"`
	ErrorKind     string        `json:"error_kind"`
	ListenerID    sql.NullInt64 `json:"listener_id"`
	BackendID     sql.NullInt64 `json:"backend_id"`
	RouteID       sql.NullInt64 `json:"route_id"`
	RouteTargetID sql.NullInt64 `json:"route_target_id"`
	WafRuleID     sql.NullInt64 `json:"waf_rule_id"`
	WafAction     string        `json:"waf_action"`
	AgentID       sql.NullInt64 `json:"agent_id"`
	RequestBytes  int64         `json:"request_bytes"`
	ResponseBytes int64         `json:"response_bytes"`
	CacheRuleID   sql.NullInt64 `json:"cache_rule_id"`
	CacheStatus   string        `json:"cache_status"`
	CacheBytes    int64         `json:"cache_bytes"`
}

type ProxyRequestRollupMinute struct {
	BucketUnixMillis int64     `json:"bucket_unix_millis"`
	Requests         int64     `json:"requests"`
	Success          int64     `json:"success"`
	ClientError      int64     `json:"client_error"`
	ServerError      int64     `json:"server_error"`
	InternalError    int64     `json:"internal_error"`
	DurationMsSum    int64     `json:"duration_ms_sum"`
	MaxDurationMs    int64     `json:"max_duration_ms"`
	SlowRequests     int64     `json:"slow_requests"`
	RequestBytes     int64     `json:"request_bytes"`
	ResponseBytes    int64     `json:"response_bytes"`
	CacheHits        int64     `json:"cache_hits"`
	CacheMisses      int64     `json:"cache_misses"`
	CacheBypasses    int64     `json:"cache_bypasses"`
	CacheStored      int64     `json:"cache_stored"`
	CacheStoreFailed int64     `json:"cache_store_failed"`
	CacheHitBytes    int64     `json:"cache_hit_bytes"`
	CacheStoredBytes int64     `json:"cache_stored_bytes"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type ProxyRequestTupleRollupMinute struct {
	BucketUnixMillis int64     `json:"bucket_unix_millis"`
	ListenerID       int64     `json:"listener_id"`
	BackendID        int64     `json:"backend_id"`
	RouteID          int64     `json:"route_id"`
	RouteTargetID    int64     `json:"route_target_id"`
	AgentID          int64     `json:"agent_id"`
	ErrorKind        string    `json:"error_kind"`
	StatusClass      int64     `json:"status_class"`
	Requests         int64     `json:"requests"`
	Success          int64     `json:"success"`
	ClientError      int64     `json:"client_error"`
	ServerError      int64     `json:"server_error"`
	InternalError    int64     `json:"internal_error"`
	DurationMsSum    int64     `json:"duration_ms_sum"`
	RequestBytes     int64     `json:"request_bytes"`
	ResponseBytes    int64     `json:"response_bytes"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type PublicAgentLabel struct {
	AgentID   int64     `json:"agent_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PublicCacheEntry struct {
	KeyDigest           string        `json:"key_digest"`
	RuleID              int64         `json:"rule_id"`
	Scope               string        `json:"scope"`
	ListenerProtocol    string        `json:"listener_protocol"`
	Host                string        `json:"host"`
	Path                string        `json:"path"`
	QueryKey            string        `json:"query_key"`
	RouteID             sql.NullInt64 `json:"route_id"`
	RouteTargetID       sql.NullInt64 `json:"route_target_id"`
	Method              string        `json:"method"`
	VaryHeadersJson     string        `json:"vary_headers_json"`
	ResponseHeadersJson string        `json:"response_headers_json"`
	StatusCode          int64         `json:"status_code"`
	BodyPath            string        `json:"body_path"`
	SizeBytes           int64         `json:"size_bytes"`
	StoredAt            time.Time     `json:"stored_at"`
	ExpiresAt           time.Time     `json:"expires_at"`
	LastAccessedAt      time.Time     `json:"last_accessed_at"`
	HitCount            int64         `json:"hit_count"`
}

type PublicCacheRule struct {
	ID                   int64     `json:"id"`
	Name                 string    `json:"name"`
	Priority             int64     `json:"priority"`
	Enabled              int64     `json:"enabled"`
	MatchJson            string    `json:"match_json"`
	RouteIdsJson         string    `json:"route_ids_json"`
	TargetIdsJson        string    `json:"target_ids_json"`
	Scope                string    `json:"scope"`
	TtlMode              string    `json:"ttl_mode"`
	TtlMillis            int64     `json:"ttl_millis"`
	QueryMode            string    `json:"query_mode"`
	QueryParamsJson      string    `json:"query_params_json"`
	VaryHeadersJson      string    `json:"vary_headers_json"`
	CacheStatusCodesJson string    `json:"cache_status_codes_json"`
	MaxObjectBytes       int64     `json:"max_object_bytes"`
	AddCacheStatusHeader int64     `json:"add_cache_status_header"`
	AllowCookieRequests  int64     `json:"allow_cookie_requests"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type PublicCacheSetting struct {
	ID                      int64     `json:"id"`
	Enabled                 int64     `json:"enabled"`
	MaxDiskBytes            int64     `json:"max_disk_bytes"`
	MaxMemoryBytes          int64     `json:"max_memory_bytes"`
	MemoryHotObjectMaxBytes int64     `json:"memory_hot_object_max_bytes"`
	MaxEntries              int64     `json:"max_entries"`
	CleanupIntervalMillis   int64     `json:"cleanup_interval_millis"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}

type PublicListener struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	BindAddress string    `json:"bind_address"`
	Port        int64     `json:"port"`
	Protocol    string    `json:"protocol"`
	Enabled     int64     `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PublicRateLimitRule struct {
	ID                     int64         `json:"id"`
	Name                   string        `json:"name"`
	Priority               int64         `json:"priority"`
	Enabled                int64         `json:"enabled"`
	Algorithm              string        `json:"algorithm"`
	LimitCount             int64         `json:"limit_count"`
	WindowMillis           int64         `json:"window_millis"`
	Burst                  int64         `json:"burst"`
	MatchJson              string        `json:"match_json"`
	KeyPartsJson           string        `json:"key_parts_json"`
	ResponseStatusCode     int64         `json:"response_status_code"`
	ResponseBody           string        `json:"response_body"`
	ResponseBodyMode       string        `json:"response_body_mode"`
	ResponseBodyTemplateID sql.NullInt64 `json:"response_body_template_id"`
	ResponseContentType    string        `json:"response_content_type"`
	ResponseHeadersJson    string        `json:"response_headers_json"`
	CreatedAt              time.Time     `json:"created_at"`
	UpdatedAt              time.Time     `json:"updated_at"`
}

type PublicResponseTemplate struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Kind        string    `json:"kind"`
	Description string    `json:"description"`
	ContentType string    `json:"content_type"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PublicRoute struct {
	ID                         int64     `json:"id"`
	ListenerID                 int64     `json:"listener_id"`
	Priority                   int64     `json:"priority"`
	HostPattern                string    `json:"host_pattern"`
	PathPrefix                 string    `json:"path_prefix"`
	TargetLoadBalancing        string    `json:"target_load_balancing"`
	IsDefault                  int64     `json:"is_default"`
	Action                     string    `json:"action"`
	RedirectTargetMode         string    `json:"redirect_target_mode"`
	RedirectTarget             string    `json:"redirect_target"`
	RedirectStatusCode         int64     `json:"redirect_status_code"`
	RedirectPreservePathSuffix int64     `json:"redirect_preserve_path_suffix"`
	RedirectPreserveQuery      int64     `json:"redirect_preserve_query"`
	Enabled                    int64     `json:"enabled"`
	CreatedAt                  time.Time `json:"created_at"`
	UpdatedAt                  time.Time `json:"updated_at"`
}

type PublicRouteTarget struct {
	ID                                  int64         `json:"id"`
	RouteID                             int64         `json:"route_id"`
	Name                                string        `json:"name"`
	Position                            int64         `json:"position"`
	PriorityGroup                       int64         `json:"priority_group"`
	Weight                              int64         `json:"weight"`
	Enabled                             int64         `json:"enabled"`
	TargetType                          string        `json:"target_type"`
	Url                                 string        `json:"url"`
	Transport                           string        `json:"transport"`
	AgentSelectorJson                   string        `json:"agent_selector_json"`
	AgentLoadBalancing                  string        `json:"agent_load_balancing"`
	TlsSkipVerify                       int64         `json:"tls_skip_verify"`
	UpstreamBasicAuthEnabled            int64         `json:"upstream_basic_auth_enabled"`
	UpstreamBasicAuthUsername           string        `json:"upstream_basic_auth_username"`
	UpstreamBasicAuthPassword           string        `json:"upstream_basic_auth_password"`
	UpstreamResponseHeaderTimeoutMillis int64         `json:"upstream_response_header_timeout_millis"`
	HealthCheckEnabled                  int64         `json:"health_check_enabled"`
	HealthCheckMethod                   string        `json:"health_check_method"`
	HealthCheckPath                     string        `json:"health_check_path"`
	HealthCheckIntervalMillis           int64         `json:"health_check_interval_millis"`
	HealthCheckTimeoutMillis            int64         `json:"health_check_timeout_millis"`
	HealthCheckHealthyThreshold         int64         `json:"health_check_healthy_threshold"`
	HealthCheckUnhealthyThreshold       int64         `json:"health_check_unhealthy_threshold"`
	HealthCheckExpectedStatusMin        int64         `json:"health_check_expected_status_min"`
	HealthCheckExpectedStatusMax        int64         `json:"health_check_expected_status_max"`
	StaticStatusCode                    int64         `json:"static_status_code"`
	StaticResponseBody                  string        `json:"static_response_body"`
	StaticResponseBodyMode              string        `json:"static_response_body_mode"`
	StaticResponseTemplateID            sql.NullInt64 `json:"static_response_template_id"`
	CreatedAt                           time.Time     `json:"created_at"`
	UpdatedAt                           time.Time     `json:"updated_at"`
}

type PublicRouteTargetResponseHeader struct {
	ID        int64     `json:"id"`
	TargetID  int64     `json:"target_id"`
	Position  int64     `json:"position"`
	Name      string    `json:"name"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PublicRouteTargetUpstreamHeader struct {
	ID        int64     `json:"id"`
	TargetID  int64     `json:"target_id"`
	Position  int64     `json:"position"`
	Name      string    `json:"name"`
	Value     string    `json:"value"`
	Sensitive int64     `json:"sensitive"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PublicTlsCertificate struct {
	ID                   int64         `json:"id"`
	ListenerID           int64         `json:"listener_id"`
	HostnamePattern      string        `json:"hostname_pattern"`
	CertPath             string        `json:"cert_path"`
	KeyPath              string        `json:"key_path"`
	Enabled              int64         `json:"enabled"`
	Source               string        `json:"source"`
	AcmeChallengeType    string        `json:"acme_challenge_type"`
	AcmeCa               string        `json:"acme_ca"`
	AcmeEmail            string        `json:"acme_email"`
	DnsCredentialID      sql.NullInt64 `json:"dns_credential_id"`
	Status               string        `json:"status"`
	LastError            string        `json:"last_error"`
	IssuedAt             sql.NullTime  `json:"issued_at"`
	ExpiresAt            sql.NullTime  `json:"expires_at"`
	NextRenewalAt        sql.NullTime  `json:"next_renewal_at"`
	LastRenewalAttemptAt sql.NullTime  `json:"last_renewal_attempt_at"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}

type PublicTlsDnsCredential struct {
	ID               int64     `json:"id"`
	Name             string    `json:"name"`
	Provider         string    `json:"provider"`
	CloudflareZoneID string    `json:"cloudflare_zone_id"`
	ApiToken         string    `json:"api_token"`
	Enabled          int64     `json:"enabled"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type PublicTrafficShaperRule struct {
	ID                     int64     `json:"id"`
	Name                   string    `json:"name"`
	Priority               int64     `json:"priority"`
	Enabled                int64     `json:"enabled"`
	BudgetScope            string    `json:"budget_scope"`
	UploadBytesPerSecond   int64     `json:"upload_bytes_per_second"`
	DownloadBytesPerSecond int64     `json:"download_bytes_per_second"`
	BurstBytes             int64     `json:"burst_bytes"`
	RequestExemptBytes     int64     `json:"request_exempt_bytes"`
	ResponseExemptBytes    int64     `json:"response_exempt_bytes"`
	MatchJson              string    `json:"match_json"`
	KeyPartsJson           string    `json:"key_parts_json"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type PublicWafCaptchaProvider struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	ProviderType string    `json:"provider_type"`
	SiteKey      string    `json:"site_key"`
	SecretKey    string    `json:"secret_key"`
	Enabled      int64     `json:"enabled"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PublicWafRule struct {
	ID                                   int64         `json:"id"`
	Name                                 string        `json:"name"`
	Priority                             int64         `json:"priority"`
	Enabled                              int64         `json:"enabled"`
	Action                               string        `json:"action"`
	ActivationMode                       string        `json:"activation_mode"`
	MatchJson                            string        `json:"match_json"`
	KeyPartsJson                         string        `json:"key_parts_json"`
	CaptchaProviderID                    sql.NullInt64 `json:"captcha_provider_id"`
	CaptchaPassTtlMillis                 int64         `json:"captcha_pass_ttl_millis"`
	WaitingRoomMaxAdmittedSessions       int64         `json:"waiting_room_max_admitted_sessions"`
	WaitingRoomAdmissionRatePerSecond    int64         `json:"waiting_room_admission_rate_per_second"`
	WaitingRoomAdmissionSessionTtlMillis int64         `json:"waiting_room_admission_session_ttl_millis"`
	WaitingRoomQueuePollIntervalMillis   int64         `json:"waiting_room_queue_poll_interval_millis"`
	WaitingRoomQueueTimeoutMillis        int64         `json:"waiting_room_queue_timeout_millis"`
	WaitingRoomPageTitle                 string        `json:"waiting_room_page_title"`
	WaitingRoomPageBody                  string        `json:"waiting_room_page_body"`
	TriggerRequestWindowMillis           int64         `json:"trigger_request_window_millis"`
	TriggerMinimumRequestRate            int64         `json:"trigger_minimum_request_rate"`
	TriggerTrafficSpikeMultiplier        float64       `json:"trigger_traffic_spike_multiplier"`
	TriggerProxyActiveRequests           int64         `json:"trigger_proxy_active_requests"`
	TriggerBackendActiveRequests         int64         `json:"trigger_backend_active_requests"`
	TriggerAgentActiveRequests           int64         `json:"trigger_agent_active_requests"`
	TriggerServerCpuPercent              float64       `json:"trigger_server_cpu_percent"`
	TriggerAgentCpuPercent               float64       `json:"trigger_agent_cpu_percent"`
	TriggerMinimumActiveMillis           int64         `json:"trigger_minimum_active_millis"`
	TriggerQuietPeriodMillis             int64         `json:"trigger_quiet_period_millis"`
	BlockResponseStatusCode              int64         `json:"block_response_status_code"`
	BlockResponseBody                    string        `json:"block_response_body"`
	BlockResponseBodyMode                string        `json:"block_response_body_mode"`
	BlockResponseTemplateID              sql.NullInt64 `json:"block_response_template_id"`
	CaptchaPageTemplateID                sql.NullInt64 `json:"captcha_page_template_id"`
	WaitingRoomPageTemplateID            sql.NullInt64 `json:"waiting_room_page_template_id"`
	BlockResponseContentType             string        `json:"block_response_content_type"`
	BlockResponseHeadersJson             string        `json:"block_response_headers_json"`
	CreatedAt                            time.Time     `json:"created_at"`
	UpdatedAt                            time.Time     `json:"updated_at"`
}

type PublicWafSetting struct {
	ID                  int64     `json:"id"`
	CookieSigningSecret string    `json:"cookie_signing_secret"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type Session struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	TokenHash  string       `json:"token_hash"`
	CreatedAt  time.Time    `json:"created_at"`
	LastSeenAt time.Time    `json:"last_seen_at"`
	ExpiresAt  time.Time    `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DisabledAt   sql.NullTime `json:"disabled_at"`
}
