// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID                 int64        `json:"id"`
	PublicID           string       `json:"public_id"`
	Name               string       `json:"name"`
	TokenHash          string       `json:"token_hash"`
	Enabled            int64        `json:"enabled"`
	LastConnectedAt    sql.NullTime `json:"last_connected_at"`
	LastDisconnectedAt sql.NullTime `json:"last_disconnected_at"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
}

type AgentStat struct {
	ID               int64         `json:"id"`
	AgentID          sql.NullInt64 `json:"agent_id"`
	ReportedAt       time.Time     `json:"reported_at"`
	MemoryMb         int64         `json:"memory_mb"`
	Goroutines       int64         `json:"goroutines"`
	ReqSuccess       int64         `json:"req_success"`
	ReqClientError   int64         `json:"req_client_error"`
	ReqServerError   int64         `json:"req_server_error"`
	ReqInternalError int64         `json:"req_internal_error"`
	BytesRx          int64         `json:"bytes_rx"`
	BytesTx          int64         `json:"bytes_tx"`
}

type Connection struct {
	ID             int64         `json:"id"`
	AgentID        sql.NullInt64 `json:"agent_id"`
	ConnectedAt    time.Time     `json:"connected_at"`
	DisconnectedAt sql.NullTime  `json:"disconnected_at"`
}

type ProxyRequestEvent struct {
	ID            int64         `json:"id"`
	OccurredAt    time.Time     `json:"occurred_at"`
	StatusCode    int64         `json:"status_code"`
	DurationMs    int64         `json:"duration_ms"`
	ErrorKind     string        `json:"error_kind"`
	ListenerID    sql.NullInt64 `json:"listener_id"`
	BackendID     sql.NullInt64 `json:"backend_id"`
	RouteID       sql.NullInt64 `json:"route_id"`
	AgentID       sql.NullInt64 `json:"agent_id"`
	RequestBytes  int64         `json:"request_bytes"`
	ResponseBytes int64         `json:"response_bytes"`
}

type PublicBackend struct {
	ID                        int64     `json:"id"`
	Name                      string    `json:"name"`
	TargetOrigin              string    `json:"target_origin"`
	BackendType               string    `json:"backend_type"`
	ForwardMode               string    `json:"forward_mode"`
	LoadBalancing             string    `json:"load_balancing"`
	TlsSkipVerify             int64     `json:"tls_skip_verify"`
	StaticStatusCode          int64     `json:"static_status_code"`
	StaticResponseBody        string    `json:"static_response_body"`
	UpstreamBasicAuthEnabled  int64     `json:"upstream_basic_auth_enabled"`
	UpstreamBasicAuthUsername string    `json:"upstream_basic_auth_username"`
	UpstreamBasicAuthPassword string    `json:"upstream_basic_auth_password"`
	Enabled                   int64     `json:"enabled"`
	CreatedAt                 time.Time `json:"created_at"`
	UpdatedAt                 time.Time `json:"updated_at"`
}

type PublicBackendAgent struct {
	BackendID int64     `json:"backend_id"`
	AgentID   int64     `json:"agent_id"`
	Position  int64     `json:"position"`
	Weight    int64     `json:"weight"`
	Enabled   int64     `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PublicBackendHeader struct {
	ID        int64     `json:"id"`
	BackendID int64     `json:"backend_id"`
	Position  int64     `json:"position"`
	Name      string    `json:"name"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PublicBackendUpstreamHeader struct {
	ID        int64     `json:"id"`
	BackendID int64     `json:"backend_id"`
	Position  int64     `json:"position"`
	Name      string    `json:"name"`
	Value     string    `json:"value"`
	Sensitive int64     `json:"sensitive"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PublicListener struct {
	ID               int64     `json:"id"`
	Name             string    `json:"name"`
	BindAddress      string    `json:"bind_address"`
	Port             int64     `json:"port"`
	Protocol         string    `json:"protocol"`
	Enabled          int64     `json:"enabled"`
	DefaultBackendID int64     `json:"default_backend_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type PublicRateLimitRule struct {
	ID                  int64     `json:"id"`
	Name                string    `json:"name"`
	Priority            int64     `json:"priority"`
	Enabled             int64     `json:"enabled"`
	Algorithm           string    `json:"algorithm"`
	LimitCount          int64     `json:"limit_count"`
	WindowMillis        int64     `json:"window_millis"`
	Burst               int64     `json:"burst"`
	MatchJson           string    `json:"match_json"`
	KeyPartsJson        string    `json:"key_parts_json"`
	ResponseStatusCode  int64     `json:"response_status_code"`
	ResponseBody        string    `json:"response_body"`
	ResponseContentType string    `json:"response_content_type"`
	ResponseHeadersJson string    `json:"response_headers_json"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type PublicRoute struct {
	ID                         int64         `json:"id"`
	ListenerID                 int64         `json:"listener_id"`
	Priority                   int64         `json:"priority"`
	HostPattern                string        `json:"host_pattern"`
	PathPrefix                 string        `json:"path_prefix"`
	BackendID                  sql.NullInt64 `json:"backend_id"`
	Action                     string        `json:"action"`
	RedirectTargetMode         string        `json:"redirect_target_mode"`
	RedirectTarget             string        `json:"redirect_target"`
	RedirectStatusCode         int64         `json:"redirect_status_code"`
	RedirectPreservePathSuffix int64         `json:"redirect_preserve_path_suffix"`
	RedirectPreserveQuery      int64         `json:"redirect_preserve_query"`
	Enabled                    int64         `json:"enabled"`
	CreatedAt                  time.Time     `json:"created_at"`
	UpdatedAt                  time.Time     `json:"updated_at"`
}

type PublicTlsCertificate struct {
	ID                   int64         `json:"id"`
	ListenerID           int64         `json:"listener_id"`
	HostnamePattern      string        `json:"hostname_pattern"`
	CertPath             string        `json:"cert_path"`
	KeyPath              string        `json:"key_path"`
	Enabled              int64         `json:"enabled"`
	Source               string        `json:"source"`
	AcmeChallengeType    string        `json:"acme_challenge_type"`
	AcmeCa               string        `json:"acme_ca"`
	AcmeEmail            string        `json:"acme_email"`
	DnsCredentialID      sql.NullInt64 `json:"dns_credential_id"`
	Status               string        `json:"status"`
	LastError            string        `json:"last_error"`
	IssuedAt             sql.NullTime  `json:"issued_at"`
	ExpiresAt            sql.NullTime  `json:"expires_at"`
	NextRenewalAt        sql.NullTime  `json:"next_renewal_at"`
	LastRenewalAttemptAt sql.NullTime  `json:"last_renewal_attempt_at"`
	CreatedAt            time.Time     `json:"created_at"`
	UpdatedAt            time.Time     `json:"updated_at"`
}

type PublicTlsDnsCredential struct {
	ID               int64     `json:"id"`
	Name             string    `json:"name"`
	Provider         string    `json:"provider"`
	CloudflareZoneID string    `json:"cloudflare_zone_id"`
	ApiToken         string    `json:"api_token"`
	Enabled          int64     `json:"enabled"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type PublicTrafficShaperRule struct {
	ID                     int64     `json:"id"`
	Name                   string    `json:"name"`
	Priority               int64     `json:"priority"`
	Enabled                int64     `json:"enabled"`
	BudgetScope            string    `json:"budget_scope"`
	UploadBytesPerSecond   int64     `json:"upload_bytes_per_second"`
	DownloadBytesPerSecond int64     `json:"download_bytes_per_second"`
	BurstBytes             int64     `json:"burst_bytes"`
	RequestExemptBytes     int64     `json:"request_exempt_bytes"`
	ResponseExemptBytes    int64     `json:"response_exempt_bytes"`
	MatchJson              string    `json:"match_json"`
	KeyPartsJson           string    `json:"key_parts_json"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type Session struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	TokenHash  string       `json:"token_hash"`
	CreatedAt  time.Time    `json:"created_at"`
	LastSeenAt time.Time    `json:"last_seen_at"`
	ExpiresAt  time.Time    `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DisabledAt   sql.NullTime `json:"disabled_at"`
}
