// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countEnabledAgentPoolBackendsWhereAgentIsLast = `-- name: CountEnabledAgentPoolBackendsWhereAgentIsLast :one
SELECT COUNT(*)
FROM public_backend_agents pba
JOIN public_backends pb ON pb.id = pba.backend_id
WHERE pba.agent_id = ?
  AND pba.enabled = 1
  AND pb.enabled = 1
  AND pb.backend_type = 'proxy_forward'
  AND pb.forward_mode = 'agent_pool'
  AND NOT EXISTS (
    SELECT 1
    FROM public_backend_agents other
    JOIN agents a ON a.id = other.agent_id
    WHERE other.backend_id = pba.backend_id
      AND other.agent_id != pba.agent_id
      AND other.enabled = 1
      AND a.enabled = 1
  )
`

func (q *Queries) CountEnabledAgentPoolBackendsWhereAgentIsLast(ctx context.Context, agentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledAgentPoolBackendsWhereAgentIsLast, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicBackendEnabledReferences = `-- name: CountPublicBackendEnabledReferences :one
SELECT
  (
    SELECT COUNT(*)
    FROM public_listeners
    WHERE default_backend_id = ? AND enabled = 1
  ) + (
    SELECT COUNT(*)
    FROM public_routes
    WHERE backend_id = ? AND enabled = 1
  ) AS references_count
`

type CountPublicBackendEnabledReferencesParams struct {
	DefaultBackendID int64 `json:"default_backend_id"`
	BackendID        int64 `json:"backend_id"`
}

func (q *Queries) CountPublicBackendEnabledReferences(ctx context.Context, arg CountPublicBackendEnabledReferencesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicBackendEnabledReferences, arg.DefaultBackendID, arg.BackendID)
	var references_count int64
	err := row.Scan(&references_count)
	return references_count, err
}

const countPublicBackends = `-- name: CountPublicBackends :one
SELECT COUNT(*) FROM public_backends
`

func (q *Queries) CountPublicBackends(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicBackends)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicListeners = `-- name: CountPublicListeners :one
SELECT COUNT(*) FROM public_listeners
`

func (q *Queries) CountPublicListeners(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicListeners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (public_id, name, token_hash, enabled)
VALUES (?, ?, ?, ?)
RETURNING id, public_id, name, token_hash, enabled, last_connected_at, last_disconnected_at, created_at, updated_at
`

type CreateAgentParams struct {
	PublicID  string `json:"public_id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	Enabled   int64  `json:"enabled"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.PublicID,
		arg.Name,
		arg.TokenHash,
		arg.Enabled,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicBackend = `-- name: CreatePublicBackend :one
INSERT INTO public_backends (
    name,
    target_origin,
    backend_type,
    forward_mode,
    load_balancing,
    tls_skip_verify,
    static_status_code,
    static_response_body,
    upstream_basic_auth_enabled,
    upstream_basic_auth_username,
    upstream_basic_auth_password,
    enabled
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, target_origin, backend_type, forward_mode, load_balancing, tls_skip_verify, static_status_code, static_response_body, upstream_basic_auth_enabled, upstream_basic_auth_username, upstream_basic_auth_password, enabled, created_at, updated_at
`

type CreatePublicBackendParams struct {
	Name                      string `json:"name"`
	TargetOrigin              string `json:"target_origin"`
	BackendType               string `json:"backend_type"`
	ForwardMode               string `json:"forward_mode"`
	LoadBalancing             string `json:"load_balancing"`
	TlsSkipVerify             int64  `json:"tls_skip_verify"`
	StaticStatusCode          int64  `json:"static_status_code"`
	StaticResponseBody        string `json:"static_response_body"`
	UpstreamBasicAuthEnabled  int64  `json:"upstream_basic_auth_enabled"`
	UpstreamBasicAuthUsername string `json:"upstream_basic_auth_username"`
	UpstreamBasicAuthPassword string `json:"upstream_basic_auth_password"`
	Enabled                   int64  `json:"enabled"`
}

func (q *Queries) CreatePublicBackend(ctx context.Context, arg CreatePublicBackendParams) (PublicBackend, error) {
	row := q.db.QueryRowContext(ctx, createPublicBackend,
		arg.Name,
		arg.TargetOrigin,
		arg.BackendType,
		arg.ForwardMode,
		arg.LoadBalancing,
		arg.TlsSkipVerify,
		arg.StaticStatusCode,
		arg.StaticResponseBody,
		arg.UpstreamBasicAuthEnabled,
		arg.UpstreamBasicAuthUsername,
		arg.UpstreamBasicAuthPassword,
		arg.Enabled,
	)
	var i PublicBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetOrigin,
		&i.BackendType,
		&i.ForwardMode,
		&i.LoadBalancing,
		&i.TlsSkipVerify,
		&i.StaticStatusCode,
		&i.StaticResponseBody,
		&i.UpstreamBasicAuthEnabled,
		&i.UpstreamBasicAuthUsername,
		&i.UpstreamBasicAuthPassword,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicBackendAgent = `-- name: CreatePublicBackendAgent :one
INSERT INTO public_backend_agents (backend_id, agent_id, position, weight, enabled)
VALUES (?, ?, ?, ?, ?)
RETURNING backend_id, agent_id, position, weight, enabled, created_at, updated_at
`

type CreatePublicBackendAgentParams struct {
	BackendID int64 `json:"backend_id"`
	AgentID   int64 `json:"agent_id"`
	Position  int64 `json:"position"`
	Weight    int64 `json:"weight"`
	Enabled   int64 `json:"enabled"`
}

func (q *Queries) CreatePublicBackendAgent(ctx context.Context, arg CreatePublicBackendAgentParams) (PublicBackendAgent, error) {
	row := q.db.QueryRowContext(ctx, createPublicBackendAgent,
		arg.BackendID,
		arg.AgentID,
		arg.Position,
		arg.Weight,
		arg.Enabled,
	)
	var i PublicBackendAgent
	err := row.Scan(
		&i.BackendID,
		&i.AgentID,
		&i.Position,
		&i.Weight,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicBackendHeader = `-- name: CreatePublicBackendHeader :one
INSERT INTO public_backend_headers (backend_id, position, name, value)
VALUES (?, ?, ?, ?)
RETURNING id, backend_id, position, name, value, created_at, updated_at
`

type CreatePublicBackendHeaderParams struct {
	BackendID int64  `json:"backend_id"`
	Position  int64  `json:"position"`
	Name      string `json:"name"`
	Value     string `json:"value"`
}

func (q *Queries) CreatePublicBackendHeader(ctx context.Context, arg CreatePublicBackendHeaderParams) (PublicBackendHeader, error) {
	row := q.db.QueryRowContext(ctx, createPublicBackendHeader,
		arg.BackendID,
		arg.Position,
		arg.Name,
		arg.Value,
	)
	var i PublicBackendHeader
	err := row.Scan(
		&i.ID,
		&i.BackendID,
		&i.Position,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicBackendUpstreamHeader = `-- name: CreatePublicBackendUpstreamHeader :one
INSERT INTO public_backend_upstream_headers (backend_id, position, name, value, sensitive)
VALUES (?, ?, ?, ?, ?)
RETURNING id, backend_id, position, name, value, sensitive, created_at, updated_at
`

type CreatePublicBackendUpstreamHeaderParams struct {
	BackendID int64  `json:"backend_id"`
	Position  int64  `json:"position"`
	Name      string `json:"name"`
	Value     string `json:"value"`
	Sensitive int64  `json:"sensitive"`
}

func (q *Queries) CreatePublicBackendUpstreamHeader(ctx context.Context, arg CreatePublicBackendUpstreamHeaderParams) (PublicBackendUpstreamHeader, error) {
	row := q.db.QueryRowContext(ctx, createPublicBackendUpstreamHeader,
		arg.BackendID,
		arg.Position,
		arg.Name,
		arg.Value,
		arg.Sensitive,
	)
	var i PublicBackendUpstreamHeader
	err := row.Scan(
		&i.ID,
		&i.BackendID,
		&i.Position,
		&i.Name,
		&i.Value,
		&i.Sensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicListener = `-- name: CreatePublicListener :one
INSERT INTO public_listeners (name, bind_address, port, protocol, enabled, default_backend_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, bind_address, port, protocol, enabled, default_backend_id, created_at, updated_at
`

type CreatePublicListenerParams struct {
	Name             string `json:"name"`
	BindAddress      string `json:"bind_address"`
	Port             int64  `json:"port"`
	Protocol         string `json:"protocol"`
	Enabled          int64  `json:"enabled"`
	DefaultBackendID int64  `json:"default_backend_id"`
}

func (q *Queries) CreatePublicListener(ctx context.Context, arg CreatePublicListenerParams) (PublicListener, error) {
	row := q.db.QueryRowContext(ctx, createPublicListener,
		arg.Name,
		arg.BindAddress,
		arg.Port,
		arg.Protocol,
		arg.Enabled,
		arg.DefaultBackendID,
	)
	var i PublicListener
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BindAddress,
		&i.Port,
		&i.Protocol,
		&i.Enabled,
		&i.DefaultBackendID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicRoute = `-- name: CreatePublicRoute :one
INSERT INTO public_routes (listener_id, priority, host_pattern, path_prefix, backend_id, enabled)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, listener_id, priority, host_pattern, path_prefix, backend_id, enabled, created_at, updated_at
`

type CreatePublicRouteParams struct {
	ListenerID  int64  `json:"listener_id"`
	Priority    int64  `json:"priority"`
	HostPattern string `json:"host_pattern"`
	PathPrefix  string `json:"path_prefix"`
	BackendID   int64  `json:"backend_id"`
	Enabled     int64  `json:"enabled"`
}

func (q *Queries) CreatePublicRoute(ctx context.Context, arg CreatePublicRouteParams) (PublicRoute, error) {
	row := q.db.QueryRowContext(ctx, createPublicRoute,
		arg.ListenerID,
		arg.Priority,
		arg.HostPattern,
		arg.PathPrefix,
		arg.BackendID,
		arg.Enabled,
	)
	var i PublicRoute
	err := row.Scan(
		&i.ID,
		&i.ListenerID,
		&i.Priority,
		&i.HostPattern,
		&i.PathPrefix,
		&i.BackendID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPublicTlsCertificate = `-- name: CreatePublicTlsCertificate :one
INSERT INTO public_tls_certificates (listener_id, hostname_pattern, cert_path, key_path, enabled)
VALUES (?, ?, ?, ?, ?)
RETURNING id, listener_id, hostname_pattern, cert_path, key_path, enabled, created_at, updated_at
`

type CreatePublicTlsCertificateParams struct {
	ListenerID      int64  `json:"listener_id"`
	HostnamePattern string `json:"hostname_pattern"`
	CertPath        string `json:"cert_path"`
	KeyPath         string `json:"key_path"`
	Enabled         int64  `json:"enabled"`
}

func (q *Queries) CreatePublicTlsCertificate(ctx context.Context, arg CreatePublicTlsCertificateParams) (PublicTlsCertificate, error) {
	row := q.db.QueryRowContext(ctx, createPublicTlsCertificate,
		arg.ListenerID,
		arg.HostnamePattern,
		arg.CertPath,
		arg.KeyPath,
		arg.Enabled,
	)
	var i PublicTlsCertificate
	err := row.Scan(
		&i.ID,
		&i.ListenerID,
		&i.HostnamePattern,
		&i.CertPath,
		&i.KeyPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, token_hash, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES (?, ?, ?)
RETURNING id, username, role
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateUserRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Role)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents
WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const deleteAgentStatsBefore = `-- name: DeleteAgentStatsBefore :exec
DELETE FROM agent_stats
WHERE reported_at < ?
`

func (q *Queries) DeleteAgentStatsBefore(ctx context.Context, reportedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteAgentStatsBefore, reportedAt)
	return err
}

const deleteDisconnectedConnectionsBefore = `-- name: DeleteDisconnectedConnectionsBefore :exec
DELETE FROM connections
WHERE disconnected_at IS NOT NULL
  AND disconnected_at < ?
`

func (q *Queries) DeleteDisconnectedConnectionsBefore(ctx context.Context, disconnectedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteDisconnectedConnectionsBefore, disconnectedAt)
	return err
}

const deleteProxyRequestEventsBefore = `-- name: DeleteProxyRequestEventsBefore :exec
DELETE FROM proxy_request_events
WHERE occurred_at < ?
`

func (q *Queries) DeleteProxyRequestEventsBefore(ctx context.Context, occurredAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteProxyRequestEventsBefore, occurredAt)
	return err
}

const deletePublicBackend = `-- name: DeletePublicBackend :exec
DELETE FROM public_backends
WHERE id = ?
`

func (q *Queries) DeletePublicBackend(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePublicBackend, id)
	return err
}

const deletePublicBackendAgents = `-- name: DeletePublicBackendAgents :exec
DELETE FROM public_backend_agents
WHERE backend_id = ?
`

func (q *Queries) DeletePublicBackendAgents(ctx context.Context, backendID int64) error {
	_, err := q.db.ExecContext(ctx, deletePublicBackendAgents, backendID)
	return err
}

const deletePublicBackendHeaders = `-- name: DeletePublicBackendHeaders :exec
DELETE FROM public_backend_headers
WHERE backend_id = ?
`

func (q *Queries) DeletePublicBackendHeaders(ctx context.Context, backendID int64) error {
	_, err := q.db.ExecContext(ctx, deletePublicBackendHeaders, backendID)
	return err
}

const deletePublicBackendUpstreamHeaders = `-- name: DeletePublicBackendUpstreamHeaders :exec
DELETE FROM public_backend_upstream_headers
WHERE backend_id = ?
`

func (q *Queries) DeletePublicBackendUpstreamHeaders(ctx context.Context, backendID int64) error {
	_, err := q.db.ExecContext(ctx, deletePublicBackendUpstreamHeaders, backendID)
	return err
}

const deletePublicListener = `-- name: DeletePublicListener :exec
DELETE FROM public_listeners
WHERE id = ?
`

func (q *Queries) DeletePublicListener(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePublicListener, id)
	return err
}

const deletePublicRoute = `-- name: DeletePublicRoute :exec
DELETE FROM public_routes
WHERE id = ?
`

func (q *Queries) DeletePublicRoute(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePublicRoute, id)
	return err
}

const deletePublicTlsCertificate = `-- name: DeletePublicTlsCertificate :exec
DELETE FROM public_tls_certificates
WHERE id = ?
`

func (q *Queries) DeletePublicTlsCertificate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePublicTlsCertificate, id)
	return err
}

const getActiveConnection = `-- name: GetActiveConnection :one
SELECT id, connected_at, disconnected_at
FROM connections
WHERE disconnected_at IS NULL
ORDER BY connected_at DESC
LIMIT 1
`

type GetActiveConnectionRow struct {
	ID             int64        `json:"id"`
	ConnectedAt    time.Time    `json:"connected_at"`
	DisconnectedAt sql.NullTime `json:"disconnected_at"`
}

func (q *Queries) GetActiveConnection(ctx context.Context) (GetActiveConnectionRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveConnection)
	var i GetActiveConnectionRow
	err := row.Scan(&i.ID, &i.ConnectedAt, &i.DisconnectedAt)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT
    s.id AS session_id,
    s.user_id,
    s.last_seen_at,
    s.expires_at,
    u.id,
    u.username,
    u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?
  AND s.revoked_at IS NULL
  AND s.expires_at > CURRENT_TIMESTAMP
  AND u.disabled_at IS NULL
`

type GetActiveSessionByTokenHashRow struct {
	SessionID  int64     `json:"session_id"`
	UserID     int64     `json:"user_id"`
	LastSeenAt time.Time `json:"last_seen_at"`
	ExpiresAt  time.Time `json:"expires_at"`
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Role       string    `json:"role"`
}

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (GetActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByTokenHash, tokenHash)
	var i GetActiveSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.ID,
		&i.Username,
		&i.Role,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, public_id, name, token_hash, enabled, last_connected_at, last_disconnected_at, created_at, updated_at
FROM agents
WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id int64) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByPublicID = `-- name: GetAgentByPublicID :one
SELECT id, public_id, name, token_hash, enabled, last_connected_at, last_disconnected_at, created_at, updated_at
FROM agents
WHERE public_id = ?
`

func (q *Queries) GetAgentByPublicID(ctx context.Context, publicID string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByPublicID, publicID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentStatsSummarySince = `-- name: GetAgentStatsSummarySince :one
SELECT
    COUNT(*) AS samples,
    CAST(COALESCE(SUM(req_success), 0) AS INTEGER) AS req_success,
    CAST(COALESCE(SUM(req_client_error), 0) AS INTEGER) AS req_client_error,
    CAST(COALESCE(SUM(req_server_error), 0) AS INTEGER) AS req_server_error,
    CAST(COALESCE(SUM(req_internal_error), 0) AS INTEGER) AS req_internal_error,
    CAST(COALESCE(SUM(bytes_rx), 0) AS INTEGER) AS bytes_rx,
    CAST(COALESCE(SUM(bytes_tx), 0) AS INTEGER) AS bytes_tx,
    CAST(COALESCE(AVG(memory_mb), 0) AS INTEGER) AS avg_memory_mb,
    CAST(COALESCE(MAX(memory_mb), 0) AS INTEGER) AS max_memory_mb,
    CAST(COALESCE(AVG(goroutines), 0) AS INTEGER) AS avg_goroutines,
    CAST(COALESCE(MAX(goroutines), 0) AS INTEGER) AS max_goroutines
FROM agent_stats
WHERE reported_at >= ?
`

type GetAgentStatsSummarySinceRow struct {
	Samples          int64 `json:"samples"`
	ReqSuccess       int64 `json:"req_success"`
	ReqClientError   int64 `json:"req_client_error"`
	ReqServerError   int64 `json:"req_server_error"`
	ReqInternalError int64 `json:"req_internal_error"`
	BytesRx          int64 `json:"bytes_rx"`
	BytesTx          int64 `json:"bytes_tx"`
	AvgMemoryMb      int64 `json:"avg_memory_mb"`
	MaxMemoryMb      int64 `json:"max_memory_mb"`
	AvgGoroutines    int64 `json:"avg_goroutines"`
	MaxGoroutines    int64 `json:"max_goroutines"`
}

func (q *Queries) GetAgentStatsSummarySince(ctx context.Context, reportedAt time.Time) (GetAgentStatsSummarySinceRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentStatsSummarySince, reportedAt)
	var i GetAgentStatsSummarySinceRow
	err := row.Scan(
		&i.Samples,
		&i.ReqSuccess,
		&i.ReqClientError,
		&i.ReqServerError,
		&i.ReqInternalError,
		&i.BytesRx,
		&i.BytesTx,
		&i.AvgMemoryMb,
		&i.MaxMemoryMb,
		&i.AvgGoroutines,
		&i.MaxGoroutines,
	)
	return i, err
}

const getConnectionSummarySince = `-- name: GetConnectionSummarySince :one
SELECT
    COUNT(*) AS total_connections,
    MAX(connected_at) AS last_connected_at,
    MAX(disconnected_at) AS last_disconnected_at
FROM connections
WHERE connected_at >= ?
`

type GetConnectionSummarySinceRow struct {
	TotalConnections   int64       `json:"total_connections"`
	LastConnectedAt    interface{} `json:"last_connected_at"`
	LastDisconnectedAt interface{} `json:"last_disconnected_at"`
}

func (q *Queries) GetConnectionSummarySince(ctx context.Context, connectedAt time.Time) (GetConnectionSummarySinceRow, error) {
	row := q.db.QueryRowContext(ctx, getConnectionSummarySince, connectedAt)
	var i GetConnectionSummarySinceRow
	err := row.Scan(&i.TotalConnections, &i.LastConnectedAt, &i.LastDisconnectedAt)
	return i, err
}

const getLatestAgentStat = `-- name: GetLatestAgentStat :one
SELECT id, agent_id, reported_at, memory_mb, goroutines, req_success, req_client_error, req_server_error, req_internal_error, bytes_rx, bytes_tx FROM agent_stats
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentStat(ctx context.Context) (AgentStat, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentStat)
	var i AgentStat
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ReportedAt,
		&i.MemoryMb,
		&i.Goroutines,
		&i.ReqSuccess,
		&i.ReqClientError,
		&i.ReqServerError,
		&i.ReqInternalError,
		&i.BytesRx,
		&i.BytesTx,
	)
	return i, err
}

const getLatestAgentStatByAgent = `-- name: GetLatestAgentStatByAgent :one
SELECT id, agent_id, reported_at, memory_mb, goroutines, req_success, req_client_error, req_server_error, req_internal_error, bytes_rx, bytes_tx
FROM agent_stats
WHERE agent_id = ?
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentStatByAgent(ctx context.Context, agentID sql.NullInt64) (AgentStat, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentStatByAgent, agentID)
	var i AgentStat
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ReportedAt,
		&i.MemoryMb,
		&i.Goroutines,
		&i.ReqSuccess,
		&i.ReqClientError,
		&i.ReqServerError,
		&i.ReqInternalError,
		&i.BytesRx,
		&i.BytesTx,
	)
	return i, err
}

const getProxyRequestSummarySince = `-- name: GetProxyRequestSummarySince :one
SELECT
    COUNT(*) AS total_requests,
    CAST(COALESCE(SUM(CASE WHEN status_code >= 200 AND status_code < 400 THEN 1 ELSE 0 END), 0) AS INTEGER) AS success,
    CAST(COALESCE(SUM(CASE WHEN status_code >= 400 AND status_code < 500 THEN 1 ELSE 0 END), 0) AS INTEGER) AS client_error,
    CAST(COALESCE(SUM(CASE WHEN status_code >= 500 THEN 1 ELSE 0 END), 0) AS INTEGER) AS server_error,
    CAST(COALESCE(SUM(CASE WHEN error_kind != '' THEN 1 ELSE 0 END), 0) AS INTEGER) AS internal_error,
    CAST(COALESCE(AVG(duration_ms), 0) AS INTEGER) AS avg_duration_ms
FROM proxy_request_events
WHERE occurred_at >= ?
`

type GetProxyRequestSummarySinceRow struct {
	TotalRequests int64 `json:"total_requests"`
	Success       int64 `json:"success"`
	ClientError   int64 `json:"client_error"`
	ServerError   int64 `json:"server_error"`
	InternalError int64 `json:"internal_error"`
	AvgDurationMs int64 `json:"avg_duration_ms"`
}

func (q *Queries) GetProxyRequestSummarySince(ctx context.Context, occurredAt time.Time) (GetProxyRequestSummarySinceRow, error) {
	row := q.db.QueryRowContext(ctx, getProxyRequestSummarySince, occurredAt)
	var i GetProxyRequestSummarySinceRow
	err := row.Scan(
		&i.TotalRequests,
		&i.Success,
		&i.ClientError,
		&i.ServerError,
		&i.InternalError,
		&i.AvgDurationMs,
	)
	return i, err
}

const getPublicBackend = `-- name: GetPublicBackend :one
SELECT id, name, target_origin, backend_type, forward_mode, load_balancing, tls_skip_verify, static_status_code, static_response_body, upstream_basic_auth_enabled, upstream_basic_auth_username, upstream_basic_auth_password, enabled, created_at, updated_at
FROM public_backends
WHERE id = ?
`

func (q *Queries) GetPublicBackend(ctx context.Context, id int64) (PublicBackend, error) {
	row := q.db.QueryRowContext(ctx, getPublicBackend, id)
	var i PublicBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetOrigin,
		&i.BackendType,
		&i.ForwardMode,
		&i.LoadBalancing,
		&i.TlsSkipVerify,
		&i.StaticStatusCode,
		&i.StaticResponseBody,
		&i.UpstreamBasicAuthEnabled,
		&i.UpstreamBasicAuthUsername,
		&i.UpstreamBasicAuthPassword,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicListener = `-- name: GetPublicListener :one
SELECT id, name, bind_address, port, protocol, enabled, default_backend_id, created_at, updated_at
FROM public_listeners
WHERE id = ?
`

func (q *Queries) GetPublicListener(ctx context.Context, id int64) (PublicListener, error) {
	row := q.db.QueryRowContext(ctx, getPublicListener, id)
	var i PublicListener
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BindAddress,
		&i.Port,
		&i.Protocol,
		&i.Enabled,
		&i.DefaultBackendID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicRoute = `-- name: GetPublicRoute :one
SELECT id, listener_id, priority, host_pattern, path_prefix, backend_id, enabled, created_at, updated_at
FROM public_routes
WHERE id = ?
`

func (q *Queries) GetPublicRoute(ctx context.Context, id int64) (PublicRoute, error) {
	row := q.db.QueryRowContext(ctx, getPublicRoute, id)
	var i PublicRoute
	err := row.Scan(
		&i.ID,
		&i.ListenerID,
		&i.Priority,
		&i.HostPattern,
		&i.PathPrefix,
		&i.BackendID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicTlsCertificate = `-- name: GetPublicTlsCertificate :one
SELECT id, listener_id, hostname_pattern, cert_path, key_path, enabled, created_at, updated_at
FROM public_tls_certificates
WHERE id = ?
`

func (q *Queries) GetPublicTlsCertificate(ctx context.Context, id int64) (PublicTlsCertificate, error) {
	row := q.db.QueryRowContext(ctx, getPublicTlsCertificate, id)
	var i PublicTlsCertificate
	err := row.Scan(
		&i.ID,
		&i.ListenerID,
		&i.HostnamePattern,
		&i.CertPath,
		&i.KeyPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, created_at, updated_at, disabled_at
FROM users
WHERE id = ? AND disabled_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, created_at, updated_at, disabled_at
FROM users
WHERE username = ? AND disabled_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const insertAgentStat = `-- name: InsertAgentStat :exec
INSERT INTO agent_stats (
    agent_id, memory_mb, goroutines, req_success, req_client_error, req_server_error, req_internal_error, bytes_rx, bytes_tx
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertAgentStatParams struct {
	AgentID          sql.NullInt64 `json:"agent_id"`
	MemoryMb         int64         `json:"memory_mb"`
	Goroutines       int64         `json:"goroutines"`
	ReqSuccess       int64         `json:"req_success"`
	ReqClientError   int64         `json:"req_client_error"`
	ReqServerError   int64         `json:"req_server_error"`
	ReqInternalError int64         `json:"req_internal_error"`
	BytesRx          int64         `json:"bytes_rx"`
	BytesTx          int64         `json:"bytes_tx"`
}

func (q *Queries) InsertAgentStat(ctx context.Context, arg InsertAgentStatParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentStat,
		arg.AgentID,
		arg.MemoryMb,
		arg.Goroutines,
		arg.ReqSuccess,
		arg.ReqClientError,
		arg.ReqServerError,
		arg.ReqInternalError,
		arg.BytesRx,
		arg.BytesTx,
	)
	return err
}

const insertConnection = `-- name: InsertConnection :one
INSERT INTO connections (agent_id, connected_at)
VALUES (?, CURRENT_TIMESTAMP)
RETURNING id
`

func (q *Queries) InsertConnection(ctx context.Context, agentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertConnection, agentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProxyRequestEvent = `-- name: InsertProxyRequestEvent :exec
INSERT INTO proxy_request_events (
    status_code, duration_ms, error_kind, listener_id, backend_id, route_id, agent_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type InsertProxyRequestEventParams struct {
	StatusCode int64         `json:"status_code"`
	DurationMs int64         `json:"duration_ms"`
	ErrorKind  string        `json:"error_kind"`
	ListenerID sql.NullInt64 `json:"listener_id"`
	BackendID  sql.NullInt64 `json:"backend_id"`
	RouteID    sql.NullInt64 `json:"route_id"`
	AgentID    sql.NullInt64 `json:"agent_id"`
}

func (q *Queries) InsertProxyRequestEvent(ctx context.Context, arg InsertProxyRequestEventParams) error {
	_, err := q.db.ExecContext(ctx, insertProxyRequestEvent,
		arg.StatusCode,
		arg.DurationMs,
		arg.ErrorKind,
		arg.ListenerID,
		arg.BackendID,
		arg.RouteID,
		arg.AgentID,
	)
	return err
}

const listAgents = `-- name: ListAgents :many
SELECT id, public_id, name, token_hash, enabled, last_connected_at, last_disconnected_at, created_at, updated_at
FROM agents
ORDER BY name ASC, public_id ASC, id ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.TokenHash,
			&i.Enabled,
			&i.LastConnectedAt,
			&i.LastDisconnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBackendAgents = `-- name: ListPublicBackendAgents :many
SELECT backend_id, agent_id, position, weight, enabled, created_at, updated_at
FROM public_backend_agents
ORDER BY backend_id ASC, position ASC, agent_id ASC
`

func (q *Queries) ListPublicBackendAgents(ctx context.Context) ([]PublicBackendAgent, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBackendAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicBackendAgent
	for rows.Next() {
		var i PublicBackendAgent
		if err := rows.Scan(
			&i.BackendID,
			&i.AgentID,
			&i.Position,
			&i.Weight,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBackendAgentsByBackend = `-- name: ListPublicBackendAgentsByBackend :many
SELECT backend_id, agent_id, position, weight, enabled, created_at, updated_at
FROM public_backend_agents
WHERE backend_id = ?
ORDER BY position ASC, agent_id ASC
`

func (q *Queries) ListPublicBackendAgentsByBackend(ctx context.Context, backendID int64) ([]PublicBackendAgent, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBackendAgentsByBackend, backendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicBackendAgent
	for rows.Next() {
		var i PublicBackendAgent
		if err := rows.Scan(
			&i.BackendID,
			&i.AgentID,
			&i.Position,
			&i.Weight,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBackendHeaders = `-- name: ListPublicBackendHeaders :many
SELECT id, backend_id, position, name, value, created_at, updated_at
FROM public_backend_headers
ORDER BY backend_id ASC, position ASC, id ASC
`

func (q *Queries) ListPublicBackendHeaders(ctx context.Context) ([]PublicBackendHeader, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBackendHeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicBackendHeader
	for rows.Next() {
		var i PublicBackendHeader
		if err := rows.Scan(
			&i.ID,
			&i.BackendID,
			&i.Position,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBackendHeadersByBackend = `-- name: ListPublicBackendHeadersByBackend :many
SELECT id, backend_id, position, name, value, created_at, updated_at
FROM public_backend_headers
WHERE backend_id = ?
ORDER BY position ASC, id ASC
`

func (q *Queries) ListPublicBackendHeadersByBackend(ctx context.Context, backendID int64) ([]PublicBackendHeader, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBackendHeadersByBackend, backendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicBackendHeader
	for rows.Next() {
		var i PublicBackendHeader
		if err := rows.Scan(
			&i.ID,
			&i.BackendID,
			&i.Position,
			&i.Name,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBackendUpstreamHeaders = `-- name: ListPublicBackendUpstreamHeaders :many
SELECT id, backend_id, position, name, value, sensitive, created_at, updated_at
FROM public_backend_upstream_headers
ORDER BY backend_id ASC, position ASC, id ASC
`

func (q *Queries) ListPublicBackendUpstreamHeaders(ctx context.Context) ([]PublicBackendUpstreamHeader, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBackendUpstreamHeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicBackendUpstreamHeader
	for rows.Next() {
		var i PublicBackendUpstreamHeader
		if err := rows.Scan(
			&i.ID,
			&i.BackendID,
			&i.Position,
			&i.Name,
			&i.Value,
			&i.Sensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBackendUpstreamHeadersByBackend = `-- name: ListPublicBackendUpstreamHeadersByBackend :many
SELECT id, backend_id, position, name, value, sensitive, created_at, updated_at
FROM public_backend_upstream_headers
WHERE backend_id = ?
ORDER BY position ASC, id ASC
`

func (q *Queries) ListPublicBackendUpstreamHeadersByBackend(ctx context.Context, backendID int64) ([]PublicBackendUpstreamHeader, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBackendUpstreamHeadersByBackend, backendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicBackendUpstreamHeader
	for rows.Next() {
		var i PublicBackendUpstreamHeader
		if err := rows.Scan(
			&i.ID,
			&i.BackendID,
			&i.Position,
			&i.Name,
			&i.Value,
			&i.Sensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicBackends = `-- name: ListPublicBackends :many
SELECT id, name, target_origin, backend_type, forward_mode, load_balancing, tls_skip_verify, static_status_code, static_response_body, upstream_basic_auth_enabled, upstream_basic_auth_username, upstream_basic_auth_password, enabled, created_at, updated_at
FROM public_backends
ORDER BY name ASC, id ASC
`

func (q *Queries) ListPublicBackends(ctx context.Context) ([]PublicBackend, error) {
	rows, err := q.db.QueryContext(ctx, listPublicBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicBackend
	for rows.Next() {
		var i PublicBackend
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetOrigin,
			&i.BackendType,
			&i.ForwardMode,
			&i.LoadBalancing,
			&i.TlsSkipVerify,
			&i.StaticStatusCode,
			&i.StaticResponseBody,
			&i.UpstreamBasicAuthEnabled,
			&i.UpstreamBasicAuthUsername,
			&i.UpstreamBasicAuthPassword,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicListeners = `-- name: ListPublicListeners :many
SELECT id, name, bind_address, port, protocol, enabled, default_backend_id, created_at, updated_at
FROM public_listeners
ORDER BY port ASC, bind_address ASC, id ASC
`

func (q *Queries) ListPublicListeners(ctx context.Context) ([]PublicListener, error) {
	rows, err := q.db.QueryContext(ctx, listPublicListeners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicListener
	for rows.Next() {
		var i PublicListener
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BindAddress,
			&i.Port,
			&i.Protocol,
			&i.Enabled,
			&i.DefaultBackendID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicRoutes = `-- name: ListPublicRoutes :many
SELECT id, listener_id, priority, host_pattern, path_prefix, backend_id, enabled, created_at, updated_at
FROM public_routes
ORDER BY listener_id ASC, priority ASC, id ASC
`

func (q *Queries) ListPublicRoutes(ctx context.Context) ([]PublicRoute, error) {
	rows, err := q.db.QueryContext(ctx, listPublicRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicRoute
	for rows.Next() {
		var i PublicRoute
		if err := rows.Scan(
			&i.ID,
			&i.ListenerID,
			&i.Priority,
			&i.HostPattern,
			&i.PathPrefix,
			&i.BackendID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTlsCertificates = `-- name: ListPublicTlsCertificates :many
SELECT id, listener_id, hostname_pattern, cert_path, key_path, enabled, created_at, updated_at
FROM public_tls_certificates
ORDER BY listener_id ASC, hostname_pattern ASC, id ASC
`

func (q *Queries) ListPublicTlsCertificates(ctx context.Context) ([]PublicTlsCertificate, error) {
	rows, err := q.db.QueryContext(ctx, listPublicTlsCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicTlsCertificate
	for rows.Next() {
		var i PublicTlsCertificate
		if err := rows.Scan(
			&i.ID,
			&i.ListenerID,
			&i.HostnamePattern,
			&i.CertPath,
			&i.KeyPath,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentConnected = `-- name: MarkAgentConnected :exec
UPDATE agents
SET last_connected_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkAgentConnected(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markAgentConnected, id)
	return err
}

const markAgentDisconnected = `-- name: MarkAgentDisconnected :exec
UPDATE agents
SET last_disconnected_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkAgentDisconnected(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markAgentDisconnected, id)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const setPublicListenerEnabled = `-- name: SetPublicListenerEnabled :one
UPDATE public_listeners
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, bind_address, port, protocol, enabled, default_backend_id, created_at, updated_at
`

type SetPublicListenerEnabledParams struct {
	Enabled int64 `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetPublicListenerEnabled(ctx context.Context, arg SetPublicListenerEnabledParams) (PublicListener, error) {
	row := q.db.QueryRowContext(ctx, setPublicListenerEnabled, arg.Enabled, arg.ID)
	var i PublicListener
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BindAddress,
		&i.Port,
		&i.Protocol,
		&i.Enabled,
		&i.DefaultBackendID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND last_seen_at < datetime('now', '-30 seconds')
`

func (q *Queries) TouchSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = ?,
    enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, public_id, name, token_hash, enabled, last_connected_at, last_disconnected_at, created_at, updated_at
`

type UpdateAgentParams struct {
	Name    string `json:"name"`
	Enabled int64  `json:"enabled"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent, arg.Name, arg.Enabled, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentToken = `-- name: UpdateAgentToken :one
UPDATE agents
SET token_hash = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, public_id, name, token_hash, enabled, last_connected_at, last_disconnected_at, created_at, updated_at
`

type UpdateAgentTokenParams struct {
	TokenHash string `json:"token_hash"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateAgentToken(ctx context.Context, arg UpdateAgentTokenParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgentToken, arg.TokenHash, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnectionDisconnected = `-- name: UpdateConnectionDisconnected :exec
UPDATE connections
SET disconnected_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateConnectionDisconnected(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateConnectionDisconnected, id)
	return err
}

const updatePublicBackend = `-- name: UpdatePublicBackend :one
UPDATE public_backends
SET name = ?,
    target_origin = ?,
    backend_type = ?,
    forward_mode = ?,
    load_balancing = ?,
    tls_skip_verify = ?,
    static_status_code = ?,
    static_response_body = ?,
    upstream_basic_auth_enabled = ?,
    upstream_basic_auth_username = ?,
    upstream_basic_auth_password = ?,
    enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, target_origin, backend_type, forward_mode, load_balancing, tls_skip_verify, static_status_code, static_response_body, upstream_basic_auth_enabled, upstream_basic_auth_username, upstream_basic_auth_password, enabled, created_at, updated_at
`

type UpdatePublicBackendParams struct {
	Name                      string `json:"name"`
	TargetOrigin              string `json:"target_origin"`
	BackendType               string `json:"backend_type"`
	ForwardMode               string `json:"forward_mode"`
	LoadBalancing             string `json:"load_balancing"`
	TlsSkipVerify             int64  `json:"tls_skip_verify"`
	StaticStatusCode          int64  `json:"static_status_code"`
	StaticResponseBody        string `json:"static_response_body"`
	UpstreamBasicAuthEnabled  int64  `json:"upstream_basic_auth_enabled"`
	UpstreamBasicAuthUsername string `json:"upstream_basic_auth_username"`
	UpstreamBasicAuthPassword string `json:"upstream_basic_auth_password"`
	Enabled                   int64  `json:"enabled"`
	ID                        int64  `json:"id"`
}

func (q *Queries) UpdatePublicBackend(ctx context.Context, arg UpdatePublicBackendParams) (PublicBackend, error) {
	row := q.db.QueryRowContext(ctx, updatePublicBackend,
		arg.Name,
		arg.TargetOrigin,
		arg.BackendType,
		arg.ForwardMode,
		arg.LoadBalancing,
		arg.TlsSkipVerify,
		arg.StaticStatusCode,
		arg.StaticResponseBody,
		arg.UpstreamBasicAuthEnabled,
		arg.UpstreamBasicAuthUsername,
		arg.UpstreamBasicAuthPassword,
		arg.Enabled,
		arg.ID,
	)
	var i PublicBackend
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetOrigin,
		&i.BackendType,
		&i.ForwardMode,
		&i.LoadBalancing,
		&i.TlsSkipVerify,
		&i.StaticStatusCode,
		&i.StaticResponseBody,
		&i.UpstreamBasicAuthEnabled,
		&i.UpstreamBasicAuthUsername,
		&i.UpstreamBasicAuthPassword,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublicListener = `-- name: UpdatePublicListener :one
UPDATE public_listeners
SET name = ?, bind_address = ?, port = ?, protocol = ?, enabled = ?, default_backend_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, bind_address, port, protocol, enabled, default_backend_id, created_at, updated_at
`

type UpdatePublicListenerParams struct {
	Name             string `json:"name"`
	BindAddress      string `json:"bind_address"`
	Port             int64  `json:"port"`
	Protocol         string `json:"protocol"`
	Enabled          int64  `json:"enabled"`
	DefaultBackendID int64  `json:"default_backend_id"`
	ID               int64  `json:"id"`
}

func (q *Queries) UpdatePublicListener(ctx context.Context, arg UpdatePublicListenerParams) (PublicListener, error) {
	row := q.db.QueryRowContext(ctx, updatePublicListener,
		arg.Name,
		arg.BindAddress,
		arg.Port,
		arg.Protocol,
		arg.Enabled,
		arg.DefaultBackendID,
		arg.ID,
	)
	var i PublicListener
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BindAddress,
		&i.Port,
		&i.Protocol,
		&i.Enabled,
		&i.DefaultBackendID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublicRoute = `-- name: UpdatePublicRoute :one
UPDATE public_routes
SET listener_id = ?, priority = ?, host_pattern = ?, path_prefix = ?, backend_id = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, listener_id, priority, host_pattern, path_prefix, backend_id, enabled, created_at, updated_at
`

type UpdatePublicRouteParams struct {
	ListenerID  int64  `json:"listener_id"`
	Priority    int64  `json:"priority"`
	HostPattern string `json:"host_pattern"`
	PathPrefix  string `json:"path_prefix"`
	BackendID   int64  `json:"backend_id"`
	Enabled     int64  `json:"enabled"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdatePublicRoute(ctx context.Context, arg UpdatePublicRouteParams) (PublicRoute, error) {
	row := q.db.QueryRowContext(ctx, updatePublicRoute,
		arg.ListenerID,
		arg.Priority,
		arg.HostPattern,
		arg.PathPrefix,
		arg.BackendID,
		arg.Enabled,
		arg.ID,
	)
	var i PublicRoute
	err := row.Scan(
		&i.ID,
		&i.ListenerID,
		&i.Priority,
		&i.HostPattern,
		&i.PathPrefix,
		&i.BackendID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePublicTlsCertificate = `-- name: UpdatePublicTlsCertificate :one
UPDATE public_tls_certificates
SET listener_id = ?, hostname_pattern = ?, cert_path = ?, key_path = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, listener_id, hostname_pattern, cert_path, key_path, enabled, created_at, updated_at
`

type UpdatePublicTlsCertificateParams struct {
	ListenerID      int64  `json:"listener_id"`
	HostnamePattern string `json:"hostname_pattern"`
	CertPath        string `json:"cert_path"`
	KeyPath         string `json:"key_path"`
	Enabled         int64  `json:"enabled"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdatePublicTlsCertificate(ctx context.Context, arg UpdatePublicTlsCertificateParams) (PublicTlsCertificate, error) {
	row := q.db.QueryRowContext(ctx, updatePublicTlsCertificate,
		arg.ListenerID,
		arg.HostnamePattern,
		arg.CertPath,
		arg.KeyPath,
		arg.Enabled,
		arg.ID,
	)
	var i PublicTlsCertificate
	err := row.Scan(
		&i.ID,
		&i.ListenerID,
		&i.HostnamePattern,
		&i.CertPath,
		&i.KeyPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBootstrapAgent = `-- name: UpsertBootstrapAgent :one
INSERT INTO agents (public_id, name, token_hash, enabled)
VALUES (?, ?, ?, 1)
ON CONFLICT(public_id) DO UPDATE SET
    name = excluded.name,
    token_hash = excluded.token_hash,
    enabled = 1,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, public_id, name, token_hash, enabled, last_connected_at, last_disconnected_at, created_at, updated_at
`

type UpsertBootstrapAgentParams struct {
	PublicID  string `json:"public_id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) UpsertBootstrapAgent(ctx context.Context, arg UpsertBootstrapAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, upsertBootstrapAgent, arg.PublicID, arg.Name, arg.TokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
