// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getLatestAgentStat = `-- name: GetLatestAgentStat :one
SELECT id, reported_at, memory_mb, goroutines, req_success, req_client_error, req_server_error, bytes_rx, bytes_tx FROM agent_stats
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentStat(ctx context.Context) (AgentStat, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentStat)
	var i AgentStat
	err := row.Scan(
		&i.ID,
		&i.ReportedAt,
		&i.MemoryMb,
		&i.Goroutines,
		&i.ReqSuccess,
		&i.ReqClientError,
		&i.ReqServerError,
		&i.BytesRx,
		&i.BytesTx,
	)
	return i, err
}

const insertAgentStat = `-- name: InsertAgentStat :exec
INSERT INTO agent_stats (
    memory_mb, goroutines, req_success, req_client_error, req_server_error, bytes_rx, bytes_tx
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type InsertAgentStatParams struct {
	MemoryMb       int64 `json:"memory_mb"`
	Goroutines     int64 `json:"goroutines"`
	ReqSuccess     int64 `json:"req_success"`
	ReqClientError int64 `json:"req_client_error"`
	ReqServerError int64 `json:"req_server_error"`
	BytesRx        int64 `json:"bytes_rx"`
	BytesTx        int64 `json:"bytes_tx"`
}

func (q *Queries) InsertAgentStat(ctx context.Context, arg InsertAgentStatParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentStat,
		arg.MemoryMb,
		arg.Goroutines,
		arg.ReqSuccess,
		arg.ReqClientError,
		arg.ReqServerError,
		arg.BytesRx,
		arg.BytesTx,
	)
	return err
}

const insertConnection = `-- name: InsertConnection :one
INSERT INTO connections (connected_at)
VALUES (CURRENT_TIMESTAMP)
RETURNING id
`

func (q *Queries) InsertConnection(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertConnection)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateConnectionDisconnected = `-- name: UpdateConnectionDisconnected :exec
UPDATE connections
SET disconnected_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateConnectionDisconnected(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateConnectionDisconnected, id)
	return err
}
