// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
RETURNING id, user_id, token_hash, created_at, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, role)
VALUES (?, ?, ?)
RETURNING id, username, role
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type CreateUserRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash, arg.Role)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Role)
	return i, err
}

const deleteAgentStatsBefore = `-- name: DeleteAgentStatsBefore :exec
DELETE FROM agent_stats
WHERE reported_at < ?
`

func (q *Queries) DeleteAgentStatsBefore(ctx context.Context, reportedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteAgentStatsBefore, reportedAt)
	return err
}

const deleteDisconnectedConnectionsBefore = `-- name: DeleteDisconnectedConnectionsBefore :exec
DELETE FROM connections
WHERE disconnected_at IS NOT NULL
  AND disconnected_at < ?
`

func (q *Queries) DeleteDisconnectedConnectionsBefore(ctx context.Context, disconnectedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteDisconnectedConnectionsBefore, disconnectedAt)
	return err
}

const deleteProxyRequestEventsBefore = `-- name: DeleteProxyRequestEventsBefore :exec
DELETE FROM proxy_request_events
WHERE occurred_at < ?
`

func (q *Queries) DeleteProxyRequestEventsBefore(ctx context.Context, occurredAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteProxyRequestEventsBefore, occurredAt)
	return err
}

const getActiveConnection = `-- name: GetActiveConnection :one
SELECT id, connected_at, disconnected_at
FROM connections
WHERE disconnected_at IS NULL
ORDER BY connected_at DESC
LIMIT 1
`

func (q *Queries) GetActiveConnection(ctx context.Context) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getActiveConnection)
	var i Connection
	err := row.Scan(&i.ID, &i.ConnectedAt, &i.DisconnectedAt)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT
    s.id AS session_id,
    s.user_id,
    s.expires_at,
    u.id,
    u.username,
    u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?
  AND s.revoked_at IS NULL
  AND s.expires_at > CURRENT_TIMESTAMP
  AND u.disabled_at IS NULL
`

type GetActiveSessionByTokenHashRow struct {
	SessionID int64     `json:"session_id"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Role      string    `json:"role"`
}

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash string) (GetActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSessionByTokenHash, tokenHash)
	var i GetActiveSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.ID,
		&i.Username,
		&i.Role,
	)
	return i, err
}

const getAgentStatsSummarySince = `-- name: GetAgentStatsSummarySince :one
SELECT
    COUNT(*) AS samples,
    CAST(COALESCE(SUM(req_success), 0) AS INTEGER) AS req_success,
    CAST(COALESCE(SUM(req_client_error), 0) AS INTEGER) AS req_client_error,
    CAST(COALESCE(SUM(req_server_error), 0) AS INTEGER) AS req_server_error,
    CAST(COALESCE(SUM(req_internal_error), 0) AS INTEGER) AS req_internal_error,
    CAST(COALESCE(SUM(bytes_rx), 0) AS INTEGER) AS bytes_rx,
    CAST(COALESCE(SUM(bytes_tx), 0) AS INTEGER) AS bytes_tx,
    CAST(COALESCE(AVG(memory_mb), 0) AS INTEGER) AS avg_memory_mb,
    CAST(COALESCE(MAX(memory_mb), 0) AS INTEGER) AS max_memory_mb,
    CAST(COALESCE(AVG(goroutines), 0) AS INTEGER) AS avg_goroutines,
    CAST(COALESCE(MAX(goroutines), 0) AS INTEGER) AS max_goroutines
FROM agent_stats
WHERE reported_at >= ?
`

type GetAgentStatsSummarySinceRow struct {
	Samples          int64 `json:"samples"`
	ReqSuccess       int64 `json:"req_success"`
	ReqClientError   int64 `json:"req_client_error"`
	ReqServerError   int64 `json:"req_server_error"`
	ReqInternalError int64 `json:"req_internal_error"`
	BytesRx          int64 `json:"bytes_rx"`
	BytesTx          int64 `json:"bytes_tx"`
	AvgMemoryMb      int64 `json:"avg_memory_mb"`
	MaxMemoryMb      int64 `json:"max_memory_mb"`
	AvgGoroutines    int64 `json:"avg_goroutines"`
	MaxGoroutines    int64 `json:"max_goroutines"`
}

func (q *Queries) GetAgentStatsSummarySince(ctx context.Context, reportedAt time.Time) (GetAgentStatsSummarySinceRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentStatsSummarySince, reportedAt)
	var i GetAgentStatsSummarySinceRow
	err := row.Scan(
		&i.Samples,
		&i.ReqSuccess,
		&i.ReqClientError,
		&i.ReqServerError,
		&i.ReqInternalError,
		&i.BytesRx,
		&i.BytesTx,
		&i.AvgMemoryMb,
		&i.MaxMemoryMb,
		&i.AvgGoroutines,
		&i.MaxGoroutines,
	)
	return i, err
}

const getConnectionSummarySince = `-- name: GetConnectionSummarySince :one
SELECT
    COUNT(*) AS total_connections,
    MAX(connected_at) AS last_connected_at,
    MAX(disconnected_at) AS last_disconnected_at
FROM connections
WHERE connected_at >= ?
`

type GetConnectionSummarySinceRow struct {
	TotalConnections   int64       `json:"total_connections"`
	LastConnectedAt    interface{} `json:"last_connected_at"`
	LastDisconnectedAt interface{} `json:"last_disconnected_at"`
}

func (q *Queries) GetConnectionSummarySince(ctx context.Context, connectedAt time.Time) (GetConnectionSummarySinceRow, error) {
	row := q.db.QueryRowContext(ctx, getConnectionSummarySince, connectedAt)
	var i GetConnectionSummarySinceRow
	err := row.Scan(&i.TotalConnections, &i.LastConnectedAt, &i.LastDisconnectedAt)
	return i, err
}

const getLatestAgentStat = `-- name: GetLatestAgentStat :one
SELECT id, reported_at, memory_mb, goroutines, req_success, req_client_error, req_server_error, req_internal_error, bytes_rx, bytes_tx FROM agent_stats
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentStat(ctx context.Context) (AgentStat, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentStat)
	var i AgentStat
	err := row.Scan(
		&i.ID,
		&i.ReportedAt,
		&i.MemoryMb,
		&i.Goroutines,
		&i.ReqSuccess,
		&i.ReqClientError,
		&i.ReqServerError,
		&i.ReqInternalError,
		&i.BytesRx,
		&i.BytesTx,
	)
	return i, err
}

const getProxyRequestSummarySince = `-- name: GetProxyRequestSummarySince :one
SELECT
    COUNT(*) AS total_requests,
    CAST(COALESCE(SUM(CASE WHEN status_code >= 200 AND status_code < 400 THEN 1 ELSE 0 END), 0) AS INTEGER) AS success,
    CAST(COALESCE(SUM(CASE WHEN status_code >= 400 AND status_code < 500 THEN 1 ELSE 0 END), 0) AS INTEGER) AS client_error,
    CAST(COALESCE(SUM(CASE WHEN status_code >= 500 THEN 1 ELSE 0 END), 0) AS INTEGER) AS server_error,
    CAST(COALESCE(SUM(CASE WHEN error_kind != '' THEN 1 ELSE 0 END), 0) AS INTEGER) AS internal_error,
    CAST(COALESCE(AVG(duration_ms), 0) AS INTEGER) AS avg_duration_ms
FROM proxy_request_events
WHERE occurred_at >= ?
`

type GetProxyRequestSummarySinceRow struct {
	TotalRequests int64 `json:"total_requests"`
	Success       int64 `json:"success"`
	ClientError   int64 `json:"client_error"`
	ServerError   int64 `json:"server_error"`
	InternalError int64 `json:"internal_error"`
	AvgDurationMs int64 `json:"avg_duration_ms"`
}

func (q *Queries) GetProxyRequestSummarySince(ctx context.Context, occurredAt time.Time) (GetProxyRequestSummarySinceRow, error) {
	row := q.db.QueryRowContext(ctx, getProxyRequestSummarySince, occurredAt)
	var i GetProxyRequestSummarySinceRow
	err := row.Scan(
		&i.TotalRequests,
		&i.Success,
		&i.ClientError,
		&i.ServerError,
		&i.InternalError,
		&i.AvgDurationMs,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, created_at, updated_at, disabled_at
FROM users
WHERE id = ? AND disabled_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, created_at, updated_at, disabled_at
FROM users
WHERE username = ? AND disabled_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const insertAgentStat = `-- name: InsertAgentStat :exec
INSERT INTO agent_stats (
    memory_mb, goroutines, req_success, req_client_error, req_server_error, req_internal_error, bytes_rx, bytes_tx
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertAgentStatParams struct {
	MemoryMb         int64 `json:"memory_mb"`
	Goroutines       int64 `json:"goroutines"`
	ReqSuccess       int64 `json:"req_success"`
	ReqClientError   int64 `json:"req_client_error"`
	ReqServerError   int64 `json:"req_server_error"`
	ReqInternalError int64 `json:"req_internal_error"`
	BytesRx          int64 `json:"bytes_rx"`
	BytesTx          int64 `json:"bytes_tx"`
}

func (q *Queries) InsertAgentStat(ctx context.Context, arg InsertAgentStatParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentStat,
		arg.MemoryMb,
		arg.Goroutines,
		arg.ReqSuccess,
		arg.ReqClientError,
		arg.ReqServerError,
		arg.ReqInternalError,
		arg.BytesRx,
		arg.BytesTx,
	)
	return err
}

const insertConnection = `-- name: InsertConnection :one
INSERT INTO connections (connected_at)
VALUES (CURRENT_TIMESTAMP)
RETURNING id
`

func (q *Queries) InsertConnection(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertConnection)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProxyRequestEvent = `-- name: InsertProxyRequestEvent :exec
INSERT INTO proxy_request_events (
    status_code, duration_ms, error_kind
) VALUES (
    ?, ?, ?
)
`

type InsertProxyRequestEventParams struct {
	StatusCode int64  `json:"status_code"`
	DurationMs int64  `json:"duration_ms"`
	ErrorKind  string `json:"error_kind"`
}

func (q *Queries) InsertProxyRequestEvent(ctx context.Context, arg InsertProxyRequestEventParams) error {
	_, err := q.db.ExecContext(ctx, insertProxyRequestEvent, arg.StatusCode, arg.DurationMs, arg.ErrorKind)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE token_hash = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateConnectionDisconnected = `-- name: UpdateConnectionDisconnected :exec
UPDATE connections
SET disconnected_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateConnectionDisconnected(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateConnectionDisconnected, id)
	return err
}
