// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetLatestAgentStat(ctx context.Context) (AgentStat, error)
	InsertAgentStat(ctx context.Context, arg InsertAgentStatParams) error
	InsertConnection(ctx context.Context) (int64, error)
	UpdateConnectionDisconnected(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
